<?

/*-------------------------------------------------------------------
Purpose: Newly Created To provide an event on click of a checkbox
 INSERTS Check Box  INTO A TABLE
	disName - printed name
	varName - name of field
	varChecked - is boxed checked variable is either "checked" or blank, and is echoed regardless
	disLabel - instructions for the field
-------------------------------------------------------------------*/

Function putCheckBoxInputEvent($disName, $varName, $varChecked, $varEvent) {
?>
   <tr>
	<td>&nbsp;</td>
	 <td>
		<input  type="checkbox" id="<? echo $varName;?>" name="<? echo $varName; ?>" value="checked" <? echo $varChecked; ?> onclick="<? echo $varEvent; ?>">&nbsp;&nbsp;
		<?echo $disName ?>	
	</td>
   </tr>
<? }
// END FUNCTION


/*-------------------------------------------------------------------
Purpose: Newly Created To provide with a tr with an id (Generally Used with show/hide js feature)
 INSERTS SELECT INPUT INTO A TABLE
	disName - printed name
	varName - name of field
	disArray - display values [key displayed, value is value]
	varSelected - Passed Value that should be initially selected.  not the displayed value
	disComments - instructions for the field
-------------------------------------------------------------------*/

Function putSelectInputShow($disName, $varName, $disArray, $varSelected, $strComment, $special, $labelFirst ='', $show,$set) {
?>
   <tr id="<?php echo $show;?>" <?php echo ($set=='true'?'style="visibility:visible;padding-bottom:10px;"':'style="visibility:hidden;padding-bottom:10px;"')?>>
	<td   valign="top">
	  <div align="right">
<? 	  echo $disName;
	  if(preg_match("/required/",$special)){
	  	echo "<font color=\"#FF0000\">*</font>";
	  }

?>

	  </div>
	</td>
     <td>

        <select name="<? echo $varName; ?>">
 		<option value=""
<? 		If (!(isset($varSelected))){
			echo "selected";
		}
	echo ">$labelFirst</option>";

		while (list ($key, $val) = each ($disArray)) {
			echo "<option value=\"$key\"";
			If ($varSelected == $val){
				echo " selected ";
			}
			echo ">$val </option> \r";
		}
		echo "</select> $strComment</td></tr>";
}
// END FUNCTION

/* -------------------------------------------------------------------
Purpose: Newly Created To provide with a tr with an id (Generally Used with show/hide js feature)
INSERTS TEXT INPUT INTO A TABLE
	disName - printed name
	varName - name of field
	varLen - length of text field
	disLen - size of text box
	varVal - value of text field
	strComment - instructions for the field
	special - wildcar for required, currency, etc....
-------------------------------------------------------------------	*/
Function putTextFieldShow($disName, $varName, $varLen, $disLen, $varVal, $strComment, $special,$show,$set) {
if(isEmpty($varLen)){
	$varLen = 50;
}
?>

<tr valign="middle" id="<?php echo $show;?>" <?php echo ($set=='true'?'style="visibility:visible;padding-bottom:10px;"':'style="visibility:hidden;padding-bottom:10px;"')?>>
	<td>
	  <div align="right" valign="middle">
	  <? echo $disName;
	  if(preg_match("/required/",$special)){
	  	echo "<font color=\"#FF0000\">*</font>";
	  }
	  	if(!(isEmpty($strComment))){
		
		echo "<span class=\"form_comments\"> <br>$strComment </span>";
	}	

	  ?>

	  </div>
	</td>
	<td>
<?
	if(preg_match("/currency/",$special)){
		echo "$";
	}
	echo "<input type=\"text\" name=\"$varName\" size=\"$disLen\" maxlength=\"$varLen\" value=\"$varVal\"> ";
?>
	</td>
   </tr>
<? }
//END FUNCTION


/*-------------------------------------------------------------------
Purpose: Newly Created To provide an event on selection (Generally Used with show/hide js feature)
 INSERTS SELECT INPUT INTO A TABLE
	disName - printed name
	varName - name of field
	disArray - display values [key displayed, value is value]
	varSelected - Passed Value that should be initially selected.  not the displayed value
	disComments - instructions for the field
-------------------------------------------------------------------*/

Function putSelectInputOnChange($disName, $varName, $disArray, $varSelected, $strComment, $special, $labelFirst ='',$event) {
?>
   <tr>
	<td   valign="top">
	  <div align="right">
<? 	  echo $disName;
	  if(preg_match("/required/",$special)){
	  	echo "<font color=\"#FF0000\">*</font>";
	  }

?>

	  </div>
	</td>
     <td>

        <select name="<? echo $varName; ?>" id="<? echo $varName; ?>" <?php echo $event ?>>
 		<option value=""
<? 		If (!(isset($varSelected))){
			echo "selected";
		}
	echo ">$labelFirst</option>";

		while (list ($key, $val) = each ($disArray)) {
			echo "<option value=\"$key\"";
			If ($varSelected == $val){
				echo " selected ";
			}
			echo ">$val </option> \r";
		}
		echo "</select> $strComment</td></tr>\r";
}
// END FUNCTION

function get_sched_dates1($dow, $startdate, $enddate, $other=''){
	//echo $dow." - ". $startdate." - ".$enddate;
	//die('stop');
	$arr_dates = array();
	$startdate2 = $startdate;
	$enddate2 = $enddate;
	 
	if($dow!="0") 
	{		
	//die('stoppp');
		if (!is_int($dow)){ 
			while(date("l", strtotime($startdate2))!=$dow)
				$startdate2 = date('Y-m-d', strtotime($startdate2." +1 day"));
	 	}else{
			while(date("w", strtotime($startdate2))!=$dow)
				$startdate2 = date('Y-m-d', strtotime($startdate2." +1 day"));
		}
			while(strtotime($startdate2) <= strtotime($enddate2)){
			if ($arr_dates[0] == '')
				$arr_dates[] = $startdate2;
			$startdate2 = date('Y-m-d', strtotime($startdate2 . " +1 week"));
			if (strtotime($startdate2)<=strtotime($enddate2))
				$arr_dates[] = $startdate2;
		}
	}
	else
	{
		//die('inside other condition when single event');
		$startdate2 = date('Y-m-d', strtotime($startdate2));
		$arr_dates[] = $startdate2; 
	}
	
	
	return $arr_dates;
}





/*-------------------------------------------------------------------	*/
/* modifies a nont tutoring session	*/
/*-------------------------------------------------------------------	*/
function non_tut_session_mod_update($ses_id, $add_date, $start_time, $end_time, $tutor_id, $name, $email, $phone, $comments,$paid,$rate){
	
	$query = "select * from PT_Other_Appt where id = $ses_id";	
	$res = runquery($query);
	$row = mysql_fetch_array($res);
	
	if ($start_time!='')
		$start_time = $start_time.":00";
	if ($end_time!='')
		$end_time = $end_time.":00";
	
	if ($add_date!=''){
		$set1.=($set1!='' ? ', ' : '')."date='$add_date'";
	}else
		$add_date = $row['date'];
	if ($start_time!=''){
		$set1.=($set1!='' ? ', ' : '')."start_time='$start_time'";
	}else
		$start_time = $row['start_time'];
	
	if ($end_time!=''){
		$set1.=($set1!='' ? ', ' : '')."end_time='$end_time'";
	}else
		$end_time = $row['end_time'];
	if ($tutor_id!='')
		$set1.=($set1!='' ? ', ' : '')."tutor_id='$tutor_id'";
	if ($name!='')
		$set1.=($set1!='' ? ', ' : '')."name='$name'";
	if ($email!='')
		$set1.=($set1!='' ? ', ' : '')."email='$email'";
	if ($phone!='')
		$set1.=($set1!='' ? ', ' : '')."phone='$phone'";
	if ($comments!='')
		$set1.=($set1!='' ? ', ' : '')."comments='$comments'";
	if ($paid=='1')
	{
		$set1.=($set1!='' ? ', ' : '')."paid=1";
		$set1.=($set1!='' ? ', ' : '')."rate='$rate'";	
	}
	else 
	{
		$set1.=($set1!='' ? ', ' : '')."paid=0";
		$set1.=($set1!='' ? ', ' : '')."rate=''";	
	}
	
			
	
	if ($name == '')
		$name = $row['name'];
	if (($add_date!='' && $row['date']!=$add_date) || ($start_time!='' && $row['start_time']!=$start_time) || ($row['end_time']!=$end_time) || ($tutor_id!='' && $row['tutor_id']!=$tutor_id) || ($name!='' && $row['name']!=$name)){
		//mofify google calendar
		set_time_limit(0);
		$tar = get_tut_info($row['tutor_id']);
		if (!$GLOBALS['x_conf_cal_token'])
			$token = gc_login();
		$row['hours'] = time_diff($row['end_time'], $row['start_time']);
		del_goog_cal($token, $row['date'], $row['start_time'], $row['hours'], $row['name'], $tar['gc_username'],$tar['gc_name']);
		if ($tutor_id && $tutor_id!=$row['tutor_id']){
			$tar = get_tut_info($tutor_id);
			if (!$GLOBALS['x_conf_cal_token'])
				$token = gc_login();
		}
		$hours = time_diff($end_time, $start_time);
		add_goog_cal($token, $add_date, $start_time, $hours, $name, $tar['gc_username'],$tar['gc_name']);
		set_time_limit(60);
	}
	
	
	$res = "UPDATE PT_Other_Appt SET $set1 where id = $ses_id";
	runquery($res);
}
 
 
 //--- new function for registering student to a class
 function class_add_student(){
	 
 }

?>