<?
/*-------------------------------------------------------------------
	gets all of the includes for Paulthetutor.com
-------------------------------------------------------------------	*/
Function Get_Paul13ToolBox() {

	include("http://www.paul13.com/Paul13ToolBox/MySQL_functions.phtml");
	include("http://www.paul13.com/Paul13ToolBox/Paul13Includes.phtml");
	include("http://www.paul13.com/Paul13ToolBox/FormFunctions.phtml");


}
?>
