<?
 $strAbsPath = "home/thepad40/public_html/";
//include($strAbsPath . "MySQL_functions.phtml");
//include($strAbsPath . "Paul13Includes.phtml");
//include($strAbsPath . "includes/MySQL_functions.phtml");

	$dbh=mysql_connect ("mysql.paulthetutors.com", "paulthetutor", "piedmont") or die ('I cannot connect to the database because: ' . mysql_error());
	mysql_select_db ("paulth40_db"); 



$homefinder = $PHP_SELF;

$numFolders = substr_count("$homefinder", "/") - 1;
$strBack = "";
$i = 0;

while($i < $numFolders){
	$strBack = $strBack . "../";
	$i = $i + 1;
}



// Puts the top of the page in place

Function putFooter($pagedetails){
?>
<br>
        </div></td>
  </tr>
</table>
<span class="footer">&nbsp;&nbsp;&nbsp;
      site designed and maintained by <a href="mailto:paul@ThePADC.com">Paul
      D. Osborne</a></span>
</body>
</html>
<? }  // end putFooter

Function putHeader($pagedetails, $strBack){
$strBack = "../";
?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>MBE Compendium</title>

<? if($pagedetails="verifyform"){?>
<script language="JavaScript" src="gen_validatorv2.js" type="text/javascript"></script>
<?}?>

</head>

<link href="<?=$strBack;?>MBECompcss.css" rel="stylesheet" type="text/css">


<body>
<table width="653" border="0" cellpadding="2">
  <tr>
    <td width="39" rowspan="2" bgcolor="#000099"><img src="<?=$strBack;?>images/50pix%20spacer.gif" width="50" height="7"></td>
    <td width="12"><img src="<?=$strBack;?>images/10pix%20spacer.gif" width="10" height="7"></td>
    <td width="582"><a href="http://www.mbecompendium.com"><img src="<?=$strBack;?>images/MBECompendium%20Header.gif" width="573" height="72" border="0"></a></td>
  </tr>
  <tr>
    <td height="344" valign="top">&nbsp;</td>
    <td valign="top">
<?
}  // end of puHeader function
?>		

<?
function putHT100LinkTable(){
?>
	<table border="1" cellpadding="2" cellspacing="0" bordercolor="#000000">
  <tr class="toplink">
      <td width="126"><div align="center">
	<a href="defbrowse.php">
	Browse</a> 
	</div></td>
 

  
    <td width="126"><div align="center">
	<a href="defget.php">
	Search
	</a> </div></td>

 	<td width="126"><div align="center">
	<a href="defusersub.php">Contribute</a> 
	</div></td>
    
    <td width="126"><div align="center">
	<a href="mailto:info@mbecompendium.com">Contact Us</a>
	</div></td>
  </tr>
</table>
<BR>
<? }

function putHT100AdminTable(){
?>
	<table border="1" cellpadding="2" cellspacing="0" bordercolor="#000000">
  <tr class="toplink">

    <td width="126"><div align="center">
	<a href="http://www.mbecompendium.com/admin/">
	Admin Home 
	</a> </div></td>
	
	 <td width="126"><div align="center">
	<a href="defform.php">
	Define a Term 
	</a> </div></td>
    
    <td width="126"><div align="center">
	<a href="allterms.php">
	Define a Requested Term</a> </div></td>
	
    	    <td width="126"><div align="center">
	<a href="http://www.mbecompendium.com">
	MBE Compendium 
	</a> </div></td>
    
	<td width="126"><div align="center">
	<a href="mailto:paul@thepadc.com">Contact Paul</a>
	</div></td>
	
  </tr>
</table><BR>
<? } ?>

<?
function putHGSERosterLinkTable(){
?>
	<table border="1" cellpadding="2" cellspacing="0" bordercolor="#000000">
  <tr class="toplink">
  
    <td width="126"><div align="center">
	<a href="index.php">
	HGSE Roster Home Page
	</a> </div></td>

    <td width="126"><div align="center">
	<a href="getinfo.php">
	Enter Your Contact Info
	</a> </div></td>

 	<td width="126"><div align="center">
	<a href="find.php">Find a Classmant</a> 
	</div></td>
    
    <td width="126"><div align="center">
	<a href="mailto:info@mbecompendium.com">Contact Us</a>
	</div></td>
  </tr>
</table>
<BR>
<? } ?>

  