<?
$strAbsPath = "/home/paulthetutor/paulthetutors.com";
include_once("config.php");
// Set up ZF
 set_include_path(get_include_path() . PATH_SEPARATOR . $strAbsPath. '/includes/library');
 date_default_timezone_set('America/Los_Angeles'); // server probably defaults to UTC
 include_once 'library/Zend/Loader.php';
 require_once $strAbsPath.'/includes/library/Zend/Loader.php';
 require_once $strAbsPath.'/includes/library/Zend/Mail.php';
// End ZF setup
include("phtml_files/webbit_includes.phtml");
include("phtml_files/vworker_includes.phtml");
//include_once($strAbsPath . "/includes/php_files/gc_updater.php");
include("php_files/google.php");
include("phtml_files/MySQL_functions.phtml");
include("phtml_files/testprep_functions.phtml");
include("phtml_files/Paul13Includes.phtml");
include("phtml_files/FormFunctions.phtml");
 
include ("get_top_links.php");

$strAbsImgPath = "/images/";

/**********************************************************
Function List
useHTTPS(): force the user to use the https version of the page is using http
rerate_sessions(family_id, start_date, end_date = NULL, student_id = NULL)
inautopay($family_id) determines if a family is registered in the autopay system.
function printarobj($arr or object)
select_testprep_student
just_select_test
select_test
select_test_source
get_testprep_student($student_id, $testprep_id=NULL, $opts)
archive($id,$strTableName)
ses_mod_loc
get_item_name($id,$table)
put_sorting_header($label, $field, $other="")
calc_sess_rate
gettutBillInfo_2010 (get's the billing info for a tutor)
client_tut_del (deletes a session )
session_del (deletes a session using just the session id )
session_add ( add a tutoring session )
tutor_info($tut_id) - given a tutors id, returns an array with all of the tutor's information
link - puts the top links for folders
get_tut_info($tutor_id) identical to tutor_info OOPS!
tutorsid_menu($selected_value, $name="tid",$callback) puts a menu for tutors
get student info functions
fam_menu($style, $inputname, $fam_id, $label, $other) - create a pull down menu for selecting a family
put_fam_menu($style="student", $inputname="fid", $fam_id=0, $label="", $other="")
  this actually puts the menu on the page
class_menu
reqToVars() - takes all of the request variables and makes them global variables
gettutBillInfo (calls gettutBillInfo2010 or gettutBillInfo2011 depending on the year)
gettutBillInfo_2011 (get's the billing info for 2011 and beyond.)
tableview (shows all of the selected column in a table, sortable by clicking title, and with action column)
get_strNotUsed (gets the values not to put in the autotables from PT_Table_Info)
get_test_type_info (gets the information about a type of test SAT, ACT, HSPT, etc...)
get_location_id
location_menu
ptts2_mail (for now simply takes calls "mail")
get_amount_due($family_id) returns to total amount due for a family
payment_process($family_id, $amount, $other=NULL)
saveStripeCustomerId($family_id, $stripe_id)
get_test_ini($test_id, $other = 0)
get_test_type($test_id)
show_sec_results($testprep_id, $section_id=NULL, $test_id=0, $section_num=0, $testhw="hw", $other=NULL)
makeCurrency( $money ) removes anything other than numbers and decimal points from variable money
**********************************************************/

function makeCurrency( $money ) {

	return preg_replace( "/[^0-9\.]/", "", $money );

}

function useHTTPS() {
	// $folder = getfolder('','','');
	// if( $folder == '' ) return;

	$son = $_SERVER['HTTPS'];

	//<>: not equal to
	if( $son <> "on" ) {

		header( "Location: https://" . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );
    	exit();	

	}

}

function rerate_sessions($family_id, $start_date, $end_date = NULL, $student_id = NULL, $month = NULL, $rerate = 0){
if(!isEmpty($start_date)){
	if(substr($start_date, 2, 1) == '-'){
		$start_date = format_date_db($start_date);
	}

	$uqs = " select id from PTAddedApp where family_id = $family_id and date >= '$start_date' ";
	
	if(!isEmpty($_REQUEST[end_date])){
		if(substr($end_date, 2, 1) == '-'){
			$end_date = format_date_db($end_date);
		}
		$uqs .= " and date <= '$end_date' ";
	}
} elseif(!isEmpty($month)){
	$uqs = "select id from PTAddedApp where family_id = $family_id and month(date) = $month ";
}



	if(!isEmpty($_REQUEST[student_id]) and $_REQUEST[student_id] <> 0 )
		$uqs .= " and student_id = $_REQUEST[student_id] ";
		
	$ids_rs = runquery($uqs);
//	echo "the qs is $uqs <BR>";
// printRS($ids_rs);

	
	while($ar_ids = mysql_fetch_array($ids_rs)){

// echo "re rating $ar_ids[id] <BR>";		
		$ar_ids[rate] = calc_sess_rate('','','','','','',$ar_ids[id]);
		// printarray($ar_ids);
		$rateAR = $ar_ids[rate];
		
		// printarray($rateAR);
		$rate = $rateAR[rate];
		$old_rate = $rateAR[old_rate];
		
		$pay = $rateAR[pay];
		$old_pay = $rateAR[old_pay];
		
// printarray($rateAR);
		
// 		echo "$rate is $old_rate not equal  or $pay <> $old_pay for $ar_ids[id]<BR>";
		
		if($rate <> $old_rate or $pay <> $old_pay){
//			echo "update PTAddedApp set rate = $rate and pay = $pay where id = $ar_ids[id]<BR>";
			$rqs = "update PTAddedApp set rate = $rate, pay = $pay where id = $ar_ids[id]";
			runquery($rqs);
		}
		
	}
	
}



/*-------------------------------------------------------------------	*/
/* prints to screen content of an 2D array				*/
/*-------------------------------------------------------------------	*/
function inautopay($family_id) {
	$qstr = "select count(*) from PT_Strip_Info where user_id = $family_id";
	$isin = singlequery($qstr);
	
	return $isin;
}


/*-------------------------------------------------------------------	*/
/* prints to screen content of an 2D array				*/
/*-------------------------------------------------------------------	*/
function printarobj($temparray){
$isob = is_object($temparray);
//echo "is object is $isob<BR>";


	if(!(is_array($temparray)) and !(is_object($temparray))){
		echo "<BR>array empty<BR>";
	} else {	
	
		while (list ($key, $value) = each($temparray)){
			if(is_string($value))
				echo "$key has the value $value<br>";
			if (is_array($value) or is_object($value)){
				printarobj($value);
			}
		} 
		echo "<BR>";
	}	
}

/*-------------------------------------------------------------------*/
/* function	archive													 */
/* marks element with $field= $arch_id in table $strTableName as archived	 */
/* 																	 */
/* 	return: returns the id number of the newly created session		 */
/*-------------------------------------------------------------------*/
function archive($arch_id, $strTableName, $field='id', $max_fields = 1){
	$Test_Q = "select count(*) id from $strTableName where $field = $arch_id";
// make sure that there is only one 
	
	$num_rows = singlequery($Test_Q);
	
	
	if($num_rows <= $max_fields and $num_rows > 0){
		$AQSt = "update $strTableName set archived = TRUE where $field = $arch_id";
		$U_id = runquery($AQSt);
	}
	
	if($num_rows = 0)
		return "no entry with $field = $arch_id exists in table $strTableName";
		
	if($num_rows > $max_fields)
		return "looks like there may be an error. More than $max_fields fields were found.";
		
return 0;	
}
	
/*-------------------------------------------------------------------*/
/* app_mod_loc modifies a appointment by deleting and reinserting it */
/* 	return: returns the id number of the newly created session		 */
/*-------------------------------------------------------------------*/

function appoint_modify($appt_id, $add_date, $location_id, $student_id, $tutor_id, $start_time, $hours, $rate_id=NULL , $sched_id='',$comments='',$name='',$rate=NULL,$pay=NULL, $opts=null){	

	//delete the old session
//	

	//add the new session
//echo '	session_add3($add_date, $location_id, $student_id, $tutor_id, $start_time, $hours, $rate_id, $sched_id,$comments,$name,$rate,$pay, $opts)<BR>';
$ins_id = session_add3($add_date, $location_id, $student_id, $tutor_id, $start_time, $hours, $rate_id, $sched_id,$comments,$name,$rate,$pay, $opts);

if($ins_id > 0){
	session_del($appt_id,'','');
} else{
	return "modification failed, please try again";
}

return $ins_id;
	
}



/*-------------------------------------------------------------------*/
/*   	put sorting headers - puts headers from an array         	 */
/* 					  	 											 */
/*-------------------------------------------------------------------*/
function get_item_name($id,$tablename,$name_field="name"){
	$NQS = "select $name_field from $tablename where id = $id";
	$name = singlequery($NQS);
	return $name;
}



/*-------------------------------------------------------------------*/
/*   	put sorting headers - puts headers from an array editing Mode- Sandip */
/* 					  	 											 */
/*-------------------------------------------------------------------*/

function put_table_cells($fields, $rs_fields, $view=1, $edit=0, $delete=0, $back="../../",$editable=null){
	while($row = mysql_fetch_array($rs_fields)){
	     		echo "<tr>";
                 $rownum=0;

		while (list ($field, $label) = each ($fields)){
          if (is_array($editable) and $editable[$rownum] !=0)
                  {
				   if ($editable[$rownum] ==1)
                         {
						   echo "<td><span id="."'".$field. "_text_" . $row['id']."'". " class='text' >".  $row[$field] . "</span> "  .
						   "<img src=".'"'.$back."../images/edit_pencil.gif".'"'. "ALT='edit' border='0' class='edit-btn' id='edit_".$field."_". $row['id']."'"." onclick= ".'"'."javascript:fieldHide('".$field."',"."'".$row['id']."')".'"'.">".
							"<textarea  rows='4' cols='50' class='editbox' id=" ."'".$field. "_input_" .$row['id']."'".">".$row[$field]."</textarea>".
							 "<img src=".'"'.$back."../images/submit.png".'"'. " border="."'0' class='save-btn' id='updt_".$field."_". $row['id']."'"." onclick= ".'"'."javascript:saveupdt('".$field."',"."'".$row['id']."','".$view."')".'"'."></td>";
					     }
                   else
				        {
                            $QStr = "SHOW COLUMNS FROM ". $view ." LIKE '" . "'". $field. "'";
                            $dropdown = mysql_set_array("", [],$QStr,$dbh);
    						echo "<td><span id="."'".$field. "_text_" . $row['id']."'". " class='text' >".  $row[$field] . "</span> "  .
						   "<img src=".'"'.$back."../images/edit_pencil.gif".'"'. "ALT='edit' border='0' class='edit-btn' id='edit_".$field."_". $row['id']."'"." onclick= ".'"'."javascript:fieldHide('".$field."',"."'".$row['id']."')".'"'.">".
                            "<select id='".$field."_input_".$row['id']."'". " class='editbox'>";
                            foreach($dropdown as $value) {
                              echo "<option value=$value>$value</option>";
                            }
						   echo "</select><img src=".'"'.$back."../images/submit.png".'"'. " border="."'0' class='save-btn' id='updt_".$field."_". $row['id']."'"." onclick= ".'"'."javascript:saveupdt('".$field."',"."'".$row['id']."','".$view."')".'"'."></td>";
				        }
	        	  }
          else
                  {
	     		    echo "<td> $row[$field] </td>";
                  }
              $rownum = $rownum + 1;
		}
		reset($fields);

		if((!(isEmpty($view))) or $edit <> 0 or $delete <> 0) echo '<td>';
		if(!(isEmpty($view))) {
			$strTable = $view;
			$tablename = $view;
?>
<a onClick="javascript:popup('show_record.php?strTable=<?=$strTable;?>&record_id=<?=$row['id'];?>','Details','600','820')">
      <img src="<?=$back;?>../images/view.gif" border="0"></a> &nbsp;
<?
}
		if($edit <> 0) echo '<a onclick="javascript:popup(\'edit_record.php?strTable=' . $tablename . '&id='.$row['id'].'\',\'Details\',\'700\',\'820\')"><img SRC="' . $back . '../images/edit_pencil.gif" ALT="edit" border="0"></a>&nbsp;';
		if($delete <> 0) echo '<a onclick="if (confirm(\'Are you sure you want to delete this record?\')) {document.form.move_id.value='.$row['id'].'; document.form.submit()}"><img SRC="' . $back . '../images/del_x.gif" ALT="delete" border="0"></a>&nbsp;';

		if($view <> 0 or $edit <> 0 or $delete <> 0) echo '</td>';
		echo "</tr>";

	}

}
/*-------------------------------------------------------------------*/
/*   	put sorting headers - puts headers from an array         	 */
/* 					  	 											 */
/*-------------------------------------------------------------------*/

function put_sorting_headers($headers, $sort=NULL, $order=NULL, $action=1, $other=""){
	echo '<tr class="l_styles">';
	while (list ($field, $label) = each ($headers)){
		put_sorting_header($label, $field, $sort, $order);
	}
	if($action) echo "<th>Action</th>";
	echo "</tr>";

}
/*-------------------------------------------------------------------*/
/*   	put sorting header - puts a header that sorts a list	 */
/* 					  	 											 */
/*-------------------------------------------------------------------*/

function put_sorting_header($label=NULL, $field=NULL, $sort=NULL, $order=NULL, $other=""){
	if(isEmpty($label)) $label = setDisplayFieldVals($field);

	echo '<th nowrap><a class=a_grey href="?'."&sort=$field&".($order == "ASC" ? "&order=DESC" : "order=ASC").'" style="text-decoration:none"><b>' . $label . '</b>'.($sort == $field ? ' <img border=0 src="../images/order_'.($order == "ASC" ? "down" : "up").'.png">' : '').'</a></th>';

}


/*-------------------------------------------------------------------*/
/*   	gets the session rate and pay based on the location			 */
/*   	takes location id											 */
/*   	returns array[rate] and array[pay]							 */
/*-------------------------------------------------------------------*/

///get the schedule for the students: day of week, hours and rate
Function pull_loc_rate($location_id, $other="") {
		$ses[rate] = singlequery("select rate from PT_Locations where id = $location_id");
		$ses[pay] = singlequery("select pay from PT_Locations where id = $location_id");
		
}
/*-------------------------------------------------------------------*/
/* gets the array with a students billing information for a month    */
/* returns a array with arBillInfo[date,rate,hours,special,comments] */
/*-------------------------------------------------------------------*/

///get the schedule for the students: day of week, hours and rate
Function gettutBillInfo_2010($month, $year, $sid, $tid, $other) {
return NULL;
  $first_of_month = "$year/$month/1";
  if($month <12){
    $next_month = $month + 1;
    $first_of_nextmonth = "$year/$next_month/1";
  } else {
    $next_year = $year + 1;
    $first_of_nextmonth = "$next_year/1/1";
  }  
  $i = 0;
    $QStr ="select a.*, t.first_name as t_first_name , t.last_name as t_last_name  from PTSchedInfo a LEFT JOIN PT_Tutors t ON a.tid = t.id where(start_date < '$first_of_nextmonth' and end_date >= '$first_of_month') and (a.sid = $sid)  ".($tid ? "and a.tid = $tid" : "");
  if(!($SchedInfoRS = mysql_query($QStr))){
    echo "$QStr <br>" . mysql_error();
  }

// first set up the schedule each scheduled day of the week assuming everything is normal
  while($arSI = mysql_fetch_array($SchedInfoRS)){
    $tempday=0;
    $arStartDate = explode("-", $arSI['start_date']);
    $arEndDate = explode("-", $arSI['end_date']);

//find the date the first day of the week of the month
$lastofmonth = date("t", mktime (0,0,0,$month,11,$year));
    do {
      $tempday = $tempday + 1;
      if($tempday == $lastofmonth){
        break;
      }  
      if(mktime(0,0,0,$month,$tempday,$year) > mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])){
        break;
      }  
    } while((date("l", mktime(0,0,0,$month,$tempday,$year)) <> $arSI['dow']) or (mktime(0,0,0,$month,$tempday,$year) < mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])));

//echo "dow is $arSI[dow]<BR>";
//echo "tempdate is $tempday<BR>";
//echo "mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])";

  if(date("l", mktime (0,0,0,$month,$tempday,$year)) == $arSI['dow']){ //if we didn't find any day that works, don't add anything to the array
    do {
// printarray($arSI);
      $printday = date("d", mktime (0,0,0,$month,$tempday,$year));
      $arBillInfo[$printday]['numday'] = $tempday;
      $arBillInfo[$printday]['date'] = date("dS \of M", mktime (0,0,0,$month,$tempday,$year));
      $arBillInfo[$printday]['hours'] = $arSI['hours'];
      $arBillInfo[$printday]['rate'] = $arSI['rate'];
      $arBillInfo[$printday]['pay'] = $arSI['pay'];
      $arBillInfo[$printday]['start_time'] = $arSI['start_time'];
      $arBillInfo[$printday]['special'] = "&nbsp;";
      $arBillInfo[$printday]['comments'] = "&nbsp;";
      $arBillInfo[$printday]['tid'] = $arSI['tid'];
      $arBillInfo[$printday]['t_name'] = $arSI['t_first_name']." ".strtoupper(substr($arSI['t_last_name'],0,1));
      $tempday = $tempday + 7;
    } while(date("n", mktime (0,0,0,$month,$tempday,$year)) == $month and (mktime(0,0,0,$month,$tempday,$year) <= mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])) );
  $useRate = $arSI['rate'];
  $useHours = $arSI['hours'];

  } //end if that ensure that the first date found is a usable date.  

} // end of basic schedule set up

// remove schedules from vacation days
  $QStr = "select id, start_date, end_date from PTVacations where start_date < '$first_of_nextmonth' and end_date >= '$first_of_month' ".($tid ? "and tid = $tid" : "");
  if(!($VacRS = mysql_query($QStr))){
    echo "$QStr <br>" . mysql_error();
  }
   while($arVac = mysql_fetch_array($VacRS)){
    $arStartDate = explode("-", $arVac['start_date']);
    $arEndDate = explode("-", $arVac['end_date']);
                //if the vacation started before the start of this month, start vacation on the first day of this month
    if (mktime(0,0,0,$month,1,$year) > mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])) {
//      echo "use first of month for $arVac[start_date] <BR>";
      $tempdate = 01;
    } else { 
//      echo "use Vacation's start date for $arVac[start_date]<BR>";
      $tempdate = $arStartDate[2];
    }
//    echo "mktime(0,0,0,$month,1,$year)   and   mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])  <BR><BR>";

// get the last day of the month
$last_day_month = date('j',mktime(0, 0, 0, $month+1, 0, $year));  

//clear the dates of the vacation    
    do {
      unset($arBillInfo[$tempdate]);
      unset($arBillInfo["0" . $tempdate]);
      $tempdate = $tempdate +1;
    } while (($tempdate <= $last_day_month) and (mktime(0,0,0,$month,$tempdate,$year) <= mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])));
  } //end while we have vacations to remove
// end removed vacation days        

// get the missed appointments.  These are the appointments that are not billed for
$QStr = "select date from PTMissedApp where month(date) = $month and year(date) = $year and (sid = $sid or sid = 0) ".($tid ? "and tid = $tid" : "");
    if(!($MARS = mysql_query($QStr))){
      echo "$QStr <br>" . mysql_error();
    }

    $QStr ="select a.*, t.first_name as t_first_name , t.last_name as t_last_name  from PTChangedApp a LEFT JOIN PT_Tutors t ON a.tid = t.id where year(a.date) = $year and month(a.date) = $month and (a.sid = $sid)  ".($tid ? "and a.tid = $tid" : "");
//  echo "changed qstr is $QStr <BR><BR><BR>";
    if(!($ChARS = mysql_query($QStr))){
      echo "$QStr <br>" . mysql_error();
    }

// printRS($ChARS);
    while($arChA = mysql_fetch_array($ChARS)){
      $arDate = explode("-", $arChA[date]);
      $printday = $arDate[2];
  // ensure that changes are being made to a date that tutor worked
      if(isset($arBillInfo[$printday]['hours'])){
  // put the date into the array
        $arBillInfo[$printday][date] = date("dS \of M", mktime (0,0,0,$arDate[1],$arDate[2],$arDate[0]));
  // add the comments if they are set
        if(!(isEmpty($arChA['comments']))){
          $arBillInfo[$printday]['comments'] = $arChA['comments'];
        }
  // put the special in, and make other appropriate changes
        if(!(isEmpty($arChA['special']))){
  // make sure that we $arChA[special] = trim($arChA[special])
        $arBillInfo[$printday]['special'] = $arChA['special'];
        switch($arChA['special']){
          case "late cancelation":
            $arBillInfo[$printday]['rate'] = $arBillInfo[$printday]['rate'] / 2;
            if((!(isEmpty($arChA['hours']))) and $arChA['hours'] > 0){
              $arBillInfo[$printday]['hours'] = $arChA['hours'];
            }
            break;

          case "changed hours":
            $arBillInfo[$printday]['hours'] = $arChA['hours'];
            $arChA['special'] = "";
            break;

          case "special rate":
            $arChA['special'] = "";
            $arBillInfo[$printday]['rate'] = $arChA['rate'];
            break;

          case "rescheduling fee":
            $arBillInfo[$printday]['hours'] = 1;
            $arBillInfo[$printday]['rate'] = 10;
            break;

          case "cancelation no charge":
            $arBillInfo[$printday]['rate'] = 0;
            break;

        }//  switch
        } // is special is set
      } // if
    }    // while appointments to change
// end of changed appointments

// get the added appts
  $QStr = "select a.*, t.first_name as t_first_name , t.last_name as t_last_name  from PTAddedApp a LEFT JOIN PT_Tutors t ON a.tid = t.id where year(a.date) = $year and month(a.date) = $month and (a.sid = $sid)  ".($tid ? "and a.tid = $tid" : "");
  if(!($AdARS = mysql_query($QStr))){
    echo "$QStr <br>" . mysql_error();
  }
  while($arAdA = mysql_fetch_array($AdARS)){
    $arDate = explode("-", $arAdA[date]);
    $printday = $arDate[2];
    $arBillInfo[$printday][date] = date("dS \of M", mktime (0,0,0,$arDate[1],$arDate[2],$arDate[0]));
    $arBillInfo[$printday]['special'] = "&nbsp;";
    $arBillInfo[$printday]['comments'] = $arAdA['comments'];
    $arBillInfo[$printday]['start_time'] = $arAdA['start_time'];
    $arBillInfo[$printday]['id'] = $arAdA['id'];
    $arBillInfo[$printday]['tid'] = $arAdA['tid'];
    $arBillInfo[$printday]['t_name'] = $arAdA['t_first_name']." ".strtoupper(substr($arAdA['t_last_name'],0,1));
    $arBillInfo[$printday]['pay'] = $arAdA['pay'];

// if the rate is not put, use the standard rate
    if(($arAdA['rate'] > 0) and $arAdA['rate'] <> null){
      $arBillInfo[$printday]['rate'] = $arAdA['rate'];
    } else {
      $arBillInfo[$printday]['rate'] = $useRate;
    }

//if the hours are left blank, insert the normal hours
    if(($arAdA['hours'] > 0) and $arAdA['hours'] <> null){
      $arBillInfo[$printday]['hours'] = $arAdA['hours'];
    } else {
      $arBillInfo[$printday]['hours'] = $useHours;
    }
  } // end of added appointments

    // remove missed appointments from arBillInfo
    while($arDates = mysql_fetch_array($MARS)){
      $arDate = explode("-", $arDates[date]);
      $printday = $arDate[2];
      unset($arBillInfo[$printday]);
    }

if(isset($arBillInfo)){  // if there is an array, sort it
  ksort($arBillInfo);
}
return $arBillInfo;
} //END FUNCTION 


/**************************************************
 deletes a session based on the session id
 ***************************************************/
function session_del($ses_id, $opts=null, $compat=null){
        !!$compat && $opts = $compat;
  $query = "select * from PTAddedApp where id = $ses_id";
  $res = runquery($query);
  $row = mysql_fetch_array($res);
  /**************Add hours back to schedule**********************/
if((!(isEmpty($row[rate_id]))) and ($row[rate_id] > 0)){
	$add_hours = $row[hours];
	$rate_id = $row[rate_id];
	
// only add th hours back if they purchased a block of hours
	$URQS = "Update PT_Rates_Fam set hours_remaining = hours_remaining + $add_hours where id = $rate_id and hours_purchased > 0";
	runquery($URQS);
	
}

  /**************delete from google calendar**********************/
  // get the tutors information  
  set_time_limit(0);
  $tar = tutor_info($row['tid']);
  $student_info = get_student_info($row['student_id']);
  $gc_name = $tar['gc_name']; //name of the calendar
  // $gc_token=gc_login(); // set up gcal object 
  $fam_name = get_fam_name($row['sid']);  
     del_goog_cal($gc_token, $row['date'], $row['start_time'], $row['hours'], $fam_name,null,$gc_name);
     set_time_limit(60);
  /**************end delete from google calendar**********************/
  $DQstr = "delete from PTAddedApp where id = $ses_id";
  $DRS = runquery($DQstr);
  $tut_name = $tar['first_name'];
        $add_date = $row['date'];
        $start_time = explode(":", $row['start_time']);
        $start_time = $start_time[0] . ":" . $start_time[1];
        $hours = $row['hours'];
        $rate = $rot['rate'];
  $msgtotut = "appointment with ". $student_info['full_name'] . " deleted on $add_date at $start_time for $hours hours of tutoring with $tut_name";
        $adminmsg = "Del ". $student_info['full_name'] ." w/ $tut_name ".date("d/n", strtotime($add_date))."@$start_time ($hours) $rate/$pay";
        if(!(isset($opts['email_paul']) && !$opts['email_paul'])) // default to sending email
          mail_alert('paul@paulthetutors.com', $adminmsg , $adminmsg, 'del');
        if(!(isset($opts['email_tut']) && !$opts['email_tut'])) // default to sending email
          mail_alert($tar['email'], $msgtotut, $msgtotut, 'del');
        return $msgtopaul;
} //session_del

/**************************************************
 Deal with deleted appointments with a tutor id
 ***************************************************/
function client_tut_del($del_date, $del_fid,$tid,$other) {
  $tinfo = tutor_info($tid);
  $MQStr = "INSERT INTO PTMissedApp (sid, date,tid) VALUES ('$del_fid', '$del_date',$tid)";
  $MRS = runquery($MQStr);
  $query = "select * from PTAddedApp where sid = '$del_fid' and date = '$del_date' and tid = $tid";
  $res = runquery($query);
  $row = mysql_fetch_array($res);
  session_del($row[id]);
  $snames = getstudentsname($del_fid);
  $tlast2 = substr($tinfo['last_name'], 0, 2);
  $tname = $tinfo['first_name'] . " " . $tlast2;
  $msgtotut = "$snames cancelled appointment on $del_date with $tname";
  $temail = $tinfo['email'];
        $adminmsg = "Del $snames w/ $tname ".date("d/n", strtotime($add_date))."@$start_time ($hours) $rate/$pay";
  mail_alert($temail, $msgtotut, $msgtotut, 'del');
  mail_alert('paul@paulthetutors.com', $adminmsg , $adminmsg, 'del');
  return "Removed the event on $del_date at $start_time.";
}

/*-------------------------------------------------------------------*/
/*   	get_loc_rate - gets the session rate and pay for a session	 */
/*   	takes 									   					 */
/*   	$process determines whether or not to delete 
				sessions if packages were purchases 				 */
/*   	returns array[rate],array[pay] and array[hours_remaining]	 */
/*-------------------------------------------------------------------*/

///determines the rate and pay for a session based on family,tutor, location.
Function calc_sess_rate($hrs, $location_id=NULL, $family_id="", $student_id="", $tutor_id=NULL, $process=1, $ses_id=NULL, $other="") {
// set all return values to NULL	
	$ses[rate] = NULL;
	$ses[pay] = NULL;
	$ses[error] = NULL;
	$ses[unbilled_hours] = 0;
	$ses[hours_purchased] = 0;
	$ses[rate_id] = NULL;
	
	$calc_rate = 0;

// if $session id is provided, get all of the other id values from there
if(!isEmpty($ses_id)){
	
	$sesQS = "select * from PTAddedApp where id = $ses_id";
	$sesAR = rowquery($sesQS);
	$ses[old_rate] = $sesAR[rate];
	$ses[old_pay] = $sesAR[pay];
	$family_id = $sesAR[family_id];
	$student_id = $sesAR[student_id];
	$location_id = $sesAR[location_id];
	if($location_id == 0)
		$location_id = 1;
	$tutor_id = $sesAR[tid];
	
// printarray($sesAR);
	
}
// throw an error if the student_id and family_id are both NULL
	if(isEmpty($student_id) and isEmpty($family_id)){
		$ses[error] = "No Family or Student was provided";
		return($ses);
	}
	if(isEmpty($location_id)){
		$ses[error] = "No location was provided";
		return($ses);
	}
// get the family_id if the student_id is sent.
	If(isEmpty($family_id)){
		$family_id = get_student_fid($student_id);
	}

	
//determine if the family is in autopay	
	$autopay = inautopay($family_id);
	

$num_rows = 0;
// if the family has a special rate for the tutor and location, use that rate and pay. Don't do this if they just have a general rate, the tutor id has to match
	$where = " ";
	$QStr = "Select id, rate, pay, hours_purchased, hours_remaining from PT_Rates_Fam where family_id = $family_id and tutor_id = $tutor_id and location_id = $location_id and archived = 0 order by id DESC";
	$RS = runquery($QStr);
// echo "tutor quesry string is $QStr ";
	
	$num_rows = mysql_num_rows($RS);

	if($num_rows >= 1 and $calc_rate == 0) { 	// if there is a rate for this family and this tutor
		$rateAR = mysql_fetch_assoc($RS);
		

		$ses[rate] = $rateAR[rate];
		$ses[pay] = $rateAR[pay];
		$ses[rate_id] = $rateAR[id];
	
		$calc_rate = 1;

		return $ses;
		
	}
	
// If the tutor has a special rate for this location, use that rate
	$where = " where tutor_id = $tutor_id and location_id = $location_id and archived = 0";
	$QStr = "Select id, rate, pay from PT_Rates_Tut $where and archived = 0 order by id DESC limit 1";
	$RS = runquery($QStr);

// echo "the tut location qs is $QStr <BR>";
	
	$num_rows = mysql_num_rows($RS);
	if($num_rows >= 1 and $calc_rate == 0) {

// echo "found loc tut rate <BR>";	

		$rateAR = mysql_fetch_assoc($RS);	
		
		// if the family is in autopay, deduct $10/hr
		if($autopay > 0){
			$rateAR[rate] = $rateAR[rate] - 10.00;
			$rateAR[rate] = number_format($rateAR[rate],2);
		}
		
		$rateAR[old_rate] = $ses[old_rate];
		$rateAR[old_pay] = $ses[old_pay];
		$calc_rate = 1;
		return $rateAR;
	
	}

// get any special rates based on a family
	$where = " where family_id = $family_id and location_id = $location_id ";// NEED TO ADD END DATE
	$QStr = "Select id, rate, pay , hours_purchased, hours_remaining from PT_Rates_Fam $where and archived = 0 order by id DESC";
	
// echo "qst is $QStr <BR>";	

	$RS = runquery($QStr);
	$num_rows = mysql_num_rows($RS);   
	if($num_rows >= 1 and $calc_rate == 0) { 	// if there is a rate for this family and this tutor
		$ses = mysql_fetch_assoc($RS);
		
		$calc_rate = 1;
		return $ses;
	}
	
// if no special rates exist, get the standard rate
	if(is_null($ses[rate]) and $calc_rate == 0){
		 $calc_rate = 1;
		 if($location_id == 0)
			 $location_id = 1;
 
		 $ses[rate] = singlequery("select rate from PT_Rates_Loc where location_id = $location_id");
		 
//If they are in autopay, subtract $10
		if($autopay > 0){
			$ses[rate] = $ses[rate] - 10;
			$ses[rate] = number_format($ses[rate],2);
		}

	}

	if(is_null($ses[pay])) $ses[pay] = singlequery("select pay from PT_Rates_Loc where location_id = $location_id");
	
	return $ses;
	
}  // end session 
/***********************************************************************
funtion session_add
input - tutor's id number
returns - the id number of the sessions that was added
************************************************************************/
function session_add3($add_date, $location_id, $student_id, $tutor_id, $start_time, $hours, $rate_id=NULL , $sched_id=-1,$comments='',$name='',$rate=NULL, $pay=NULL, $opts=null) {
	
// echo "opts is <BR>";
// printarray($opts);	


	$family_id = get_student_fid($student_id);
	$name = get_student_name($student_id);
	
	if(($opts[set_money] <> 1) or ((isEmpty($pay)) or (isEmpty($rate)))){
		$RPar = calc_sess_rate($hours, $location_id,"",$student_id,$tutor_id);

// echo "$RPar = calc_se_rate($hours, $location_id,'',$student_id,$tutor_id);";
// printarray($RPar);

	}


// printarray($RPar);		
	
	if(isEmpty($pay) or ($opts[set_money] <> 1)) 
		$pay = $RPar[pay];
	if(isEmpty($rate) or ($opts[set_money] <> 1))  
		$rate = $RPar[rate];
	
	$rate_id = $RPar[rate_id];
		
	$tid = $tutor_id;		
			
			
	//		session_add($add_date,$start_time,'',$hours,$rate,$pay,$tutor_id,$student_name, $sched_id, $comments, $opts, $student_id,$location_id);
	//function session_add($add_date, $start_time, $family_id, $hours, $rate, $pay, $tid, $name='', $sched_id='',$comments = '', $opts=NULL, $student_id='', $location_id=0) {
	
	  
	  $AQStr = "INSERT INTO PTAddedApp (sid,family_id, student_id, date, hours, rate, start_time, pay, tid, name, sched_id,comments,location_id,rate_id) VALUES ('$family_id','$family_id','$student_id', '$add_date', '$hours', '$rate', '$start_time', '$pay', $tid, '".addslashes($name)."', '$sched_id','$comments',$location_id,'$rate_id')";
	  
// echo "insert session qs is $AQStr <BR>";	  
	  
	  $temp_ses_id = runquery($AQStr);
// runquery returns the insertion id if it inserts a value
//	 $temp_ses_id =  mysql_insert_id($ARS);
	 
	 	$AQStr2 = "INSERT INTO ZZ_PTAddedApp_All (sess_id,sid,family_id, student_id, date, hours, rate, start_time, pay, tid, name, sched_id,comments,location_id,rate_id) VALUES ($temp_ses_id,'$family_id','$family_id','$student_id', '$add_date', '$hours', '$rate', '$start_time', '$pay', $tid, '".addslashes($name)."', '$sched_id','$comments',$location_id,'$rate_id')";
	  $ARS2 = runquery($AQStr2);

	  
	  
// echo "insert quesry is $AQStr <BR><BR>";	  
	
	// put the google calendar functions
	  $tar = tutor_info($tid);
	
	  $start_time = explode(":", $start_time);
	  $start_time = $start_time[0] . ":" . $start_time[1];
	// get the tutors information  
	  set_time_limit(0);
	  $gc_name = $tar['gc_name']; //name of the calendar
	  $tut_email = $tar['email'];
	  $tut_name = $tar['first_name'];
	//  if (!$GLOBALS['x_conf_cal_token'])
	//    $gc_token=gc_login(); // get's login info
	// get family name
	  $fam_name = get_fam_name($family_id);  
	// add the informatoin to the google calendar  
	// #echo "<br><br>".__FILE__.":".__LINE__."add_goog_cal($gc_token, '$add_date', '$start_time', $hours, $fam_name,null,$gc_name)<BR><BR>";
	//   add_goog_cal($gc_token, $add_date, $start_time.":00", $hours, $fam_name,null,$gc_name);
	   set_time_limit(10);
	
	//send an email
	  $snames = getstudentsname($family_id);
	  $msgtopaul = "$fam_name added an appointment on $add_date at $start_time for $hours hours of tutoring with $tut_name";
	$adminmsg = "Add $snames w/ $tut_name ".date("d/n", strtotime($add_date))."@$start_time ($hours) $rate/$pay";
	if(!(isset($opts['email_paul']) && !$opts['email_paul'])) // default to sending email
	  mail_alert('admin@paulthetutors.com', $adminmsg , $adminmsg, 'add');
	/****New Code Added by Sandip to send a mail to the tutor when a new session is added with their profile**/  
	if(isset($tut_email)) // default to sending email
	  mail_alert($tut_email, $adminmsg , $msgtopaul, 'add');
	/****End Of New Code - Sandip 09/19/14**/
//	if(!(isset($opts['email_tut']) && !$opts['email_tut'])) // default to sending email
//	  mail_alert($tut_email, $msgtopaul, $msgtopaul, 'add');

return $temp_ses_id;

}

/***********************************************************************
funtion session_add
input - tutor's id number
returns - array with all of the tutor's information
************************************************************************/
function session_add2($add_date, $start_time, $add_fid, $hours, $rate, $pay, $tid, $contact, $student_id, $name='', $sched_id=-1,$comments='',$opts=null,$location_id=0) {




  return session_add($add_date, $start_time, $add_fid, $hours, $rate, $pay, $tid, $name, $sched_id,$comments, $opts, $student_id,$location_id=0);
}  

/***********************************************************************
funtion session_add
input - tutor's id number
returns - array with all of the tutor's information
************************************************************************/
function session_add($add_date, $start_time, $family_id, $hours, $rate, $pay, $tid, $name='', $sched_id=-1,$comments = '', $opts=NULL, $student_id='', $location_id=0) {
  if(isEmpty($tid)) {
    $tid = 1;
  }
  $start_time = $start_time;
  if(isEmpty($hours)){
    $hours = 1;
  }  

  if(isEmpty($hours)){
    $hours = 1;
  }  

if(isEmpty($student_id)){
  	$student_id = singlequery("select id from PTStudentInfo_New where fid = $family_id LIMIT 1");
}

if(isEmpty($family_id)){
	$family_id = singlequery("select fid from PTStudentInfo_New where id = $student_id");
}	

$name = get_student_name($student_id);
  
  $AQStr = "INSERT INTO PTAddedApp (sid, family_id, student_id, date, hours, rate, start_time, pay, tid, name, sched_id,comments,location_id) VALUES ('$family_id','$family_id','$student_id', '$add_date', '$hours', '$rate', '$start_time', '$pay', $tid, '".addslashes($name)."', '$sched_id','$comments',$location_id)";
  $temp_ses_id = runquery($AQStr);
  
	 	$AQStr2 = "INSERT INTO ZZ_PTAddedApp_All (sess_id,sid,family_id, student_id, date, hours, rate, start_time, pay, tid, name, sched_id,comments,location_id,rate_id) VALUES ($temp_ses_id,'$family_id','$family_id','$student_id', '$add_date', '$hours', '$rate', '$start_time', '$pay', $tid, '".addslashes($name)."', '$sched_id','$comments',$location_id,'$rate_id')";
	  $ARS2 = runquery($AQStr2);


// put the google calendar functions
  $tar = tutor_info($tid);

  $start_time = explode(":", $start_time);
  $start_time = $start_time[0] . ":" . $start_time[1];
// get the tutors information  
  set_time_limit(0);
  $gc_name = $tar['gc_name']; //name of the calendar
  $tut_email = $tar['email'];
  $tut_name = $tar['first_name'];
//  if (!$GLOBALS['x_conf_cal_token'])
//    $gc_token=gc_login(); // get's login info
// get family name
  $fam_name = get_fam_name($family_id);  
// add the informatoin to the google calendar  
// #echo "<br><br>".__FILE__.":".__LINE__."add_goog_cal($gc_token, '$add_date', '$start_time', $hours, $fam_name,null,$gc_name)<BR><BR>";
//   add_goog_cal($gc_token, $add_date, $start_time.":00", $hours, $fam_name,null,$gc_name);
   set_time_limit(10);

//send an email
  $snames = getstudentsname($family_id);
  $msgtopaul = "$fam_name added an appointment on $add_date at $start_time for $hours hours of tutoring with $tut_name";
        $adminmsg = "Add $snames w/ $tut_name ".date("d/n", strtotime($add_date))."@$start_time ($hours) $rate/$pay";
        if(!(isset($opts['email_paul']) && !$opts['email_paul'])) // default to sending email
          mail_alert('paul@paulthetutors.com', $adminmsg , $adminmsg, 'add');
        if(!(isset($opts['email_tut']) && !$opts['email_tut'])) // default to sending email
          mail_alert($tut_email, $msgtopaul, $msgtopaul, 'add');
if($opts[returnid] == 1)
	 $msgtopaul =  $temp_ses_id;


return $msgtopaul;
}

/***********************************************************************
funtion tutor_info
input - tutor's id number
returns - array with all of the tutor's information
***********************************************************************/
function tutor_info($tutor_id){
  $TQStr = "select * from PT_Tutors where id = $tutor_id";
// echo "test tut info $TQStr<BR>";
  $TRS = runquery($TQStr);
  $Tar = mysql_fetch_array($TRS);
  return $Tar;
}

/***********************************************************************
funtion get_top_links
***********************************************************************/

function get_top_links($folder){
switch ($folder) {
    case "admin":
        $links[1][0] = FULL_BASE_PATH."/admin/index.php";
    $links[1][1] = "Admin Home";
        $links[2][0] = FULL_BASE_PATH."/admin/calendar_action.php";
    $links[2][1] = "Calendar";
    $links[3][0] = FULL_BASE_PATH."/admin/billing.php";
    $links[3][1] = "Accounting";
        $links[4][0] = FULL_BASE_PATH."/admin/showbills_new.php";
    $links[4][1] = "Show Bills";
        $links[5][0] = FULL_BASE_PATH."/admin/sendbills_new.php";
    $links[5][1] = "Send Bills";
        $links[6][0] = FULL_BASE_PATH."/admin/families.php";
    $links[6][1] = "Families";
        $links[7][0] = FULL_BASE_PATH."/admin/tutorsinfo.php";
    $links[7][1] = "Tutors";
    $links[8][0] = FULL_BASE_PATH;
    $links[8][1] = "Paul the Tutor's";
        break;

    case "parents":
        //$links[1][0] = FULL_BASE_PATH.$folder."/index.php";
    	$links[1][0] = FULL_BASE_PATH."/index.php";
    $links[1][1] = "Paul the Tutor's";
        $links[2][0] = FULL_BASE_PATH."/parents";
    $links[2][1] = "Parent's Home";
        $links[3][0] = FULL_BASE_PATH."/parents/viewbill.php";
    $links[3][1] = "Accounting";
        $links[4][0] = FULL_BASE_PATH."/parents/edit_info_full.php";
    $links[4][1] = "Edit Information";
        $links[5][0] = "tutorsinfo.php";
    $links[5][1] = "Tutor's Info";
        $links[6][0] = FULL_BASE_PATH."/parents/login_parents.php?logout=1";
    $links[6][1] = "Log Out";
        $links[7][0] = FULL_BASE_PATH."/contact.php";
    $links[7][1] = "Book a Session";
        $links[8][0] = FULL_BASE_PATH."/contact.php";
    $links[8][1] = "Contact Us";
        break;

    case "tutors":
        $links[1][0] = "index_tutors.php";
    $links[1][1] = "Tutors' Home";
        $links[2][0] = "calendar_action.php";
    $links[2][1] = "Calendar";
        $links[3][0] = "show_bills.php";
    $links[3][1] = "Month's Sessions";
        $links[4][0] = "comments_inprogress.php";
    $links[4][1] = "Notes";
        $links[8][0] = FULL_BASE_PATH."/tutors/tutlogin.php?logout=1";
    $links[8][1] = "Log Out";
        $links[6][0] = FULL_BASE_PATH."/tutors/schedules.php";
    $links[6][1] = "Schedules";
        $links[7][0] = FULL_BASE_PATH."/tutors/work_hours_list.php";
    $links[7][1] = "Non-tutoring";
        $links[5][0] = FULL_BASE_PATH."/contact.php";
    $links[5][1] = "Contact Us";
        break;
        
    case "ldsatadmin":
        $links[1][0] = "index.php";
        $links[1][1] = "Test Prep Admin";
        $links[2][0] = "get_grsec.php";
        $links[2][1] = "Score Section";
        $links[3][0] = "get_grtest.php";
        $links[3][1] = "Score Test";
        $links[4][0] = "score_sum.php";
        $links[4][1] = "Result Summary";
        $links[5][0] = "standardized_tests.php";
        $links[5][1] = "Tests' Info";
        $links[6][0] = "gettestinfo.php";
        $links[6][1] = "New Test";
        $links[7][0] = "class_rosters.php";
        $links[7][1] = "Classes";
        $links[8][0] = "homework.php";
        $links[8][1] = "Homework";
        break;
        
    case "students":
        $links[1][0] = "index.php";
        $links[1][1] = "My Homepage";
        $links[2][0] = "homework.php";
        $links[2][1] = "Homework";
        $links[3][0] = "get_grsec.php";
        $links[3][1] = "Score A Section";
        $links[4][0] = "get_grtest.php";
        $links[4][1] = "Score A Test";
        $links[5][0] = "ans_grader.php";
        $links[5][1] = "Results Summary";
        $links[6][0] = "get_grsec.php?action=ans_grader.php";
        $links[6][1] = "Test Results";
        $links[7][0] = "get_grsec.php?action=ans_grader.php";
        $links[7][1] = "Sec Results";
        $links[8][0] = "login.php?logout=1";
        $links[8][1] = "Log Out";
        break;
        
    default:
        $links[1][0] = FULL_BASE_PATH."/index.php";
  $links[1][1] = "Home";
        $links[2][0] = FULL_BASE_PATH."/services.php";
  $links[2][1] = "Services";
  if (stristr($_SERVER['PHP_SELF'], "index")){
           $links[5][0] = FULL_BASE_PATH."/faq.php";
    $links[5][1] = "FAQ";
  }else{
    $links[5][0] = FULL_BASE_PATH."/aboutus.php";
    $links[5][1] = "About Us";
  }
        $links[3][0] = FULL_BASE_PATH."/newparents.php";
  $links[3][1] = "Parents";
        $links[4][0] = FULL_BASE_PATH."/locations.php";
  $links[4][1] = "Locations";
        $links[6][0] = FULL_BASE_PATH."/login.php";
  $links[6][1] = "Login";
        $links[7][0] = FULL_BASE_PATH."/contact.php";
  $links[7][1] = "Book a Session";
        $links[8][0] = FULL_BASE_PATH."/contact.php";
  $links[8][1] = "Contact Us";
   }  

  return($links);
}

/***********************************************************************
funtion put header for paulthetutors.com 2013
***********************************************************************/
function put_header_2013($page_title="Paul the Tutor's Education Center", $strBack=NULL, $folder=NULL,$other=NULL){
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="google-site-verification" content="unawIL1y5LuUsTZ1mQiUnNzCruL_L1mktNdyqCjBQIg" />
<meta http-equiv="pragma" content="no-cache" />
<meta name="keywords" content="Tutoring, LD tutoring, Learning Disability, Learning Disability SAT, LD SAT, SAT, SAT Prep, LD SAT Prep, LD Test Prep, LD SAT Tutoring" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$page_title;?></title>
<link href="includes/css_files/styles_main.css" rel="stylesheet" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script src="includes/js_files/slides.min.jquery.js"></script>
<script type="text/javascript" src="includes/js_files/ddaccordion.js">

/***********************************************
* Accordion Content script- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* Visit http://www.dynamicDrive.com for hundreds of DHTML scripts
* This notice must stay intact for legal use
***********************************************/

</script>
<script type="text/javascript">
//Initialize first demo:
ddaccordion.init({
	headerclass: "accordion_header", //Shared CSS class name of headers group
	contentclass: "accordion_section", //Shared CSS class name of contents group
	revealtype: "mouseover", //Reveal content when user clicks or onmouseover the header? Valid value: "click", "clickgo", or "mouseover"
	mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
	collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
	defaultexpanded: [], //index of content(s) open by default [index1, index2, etc]. [] denotes no content.
	onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
	animatedefault: false, //Should contents open by default be animated into view?
	scrolltoheader: false, //scroll to header each time after it's been expanded by the user?
	persiststate: false, //persist state of opened contents within browser session?
	toggleclass: ["", "openpet"], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
	togglehtml: ["none", "", ""], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
	animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
	oninit:function(expandedindices){ //custom code to run when headers have initalized
		//do nothing
	},
	onopenclose:function(header, index, state, isuseractivated){ //custom code to run whenever a header is opened or closed
		//do nothing
	}
})

</script>
<script>
    $(function(){
		
			$("#accordion").bind('mouseleave', function()
			{
				ddaccordion.collapseall("accordion_header");
			});
    	
		$("#slides").slides({
			preload: true,
				slideSpeed: 2000, 
				preloadImage: 'includes/images/loading.gif',
				play: 5000,
				pause: 2000,
				hoverPause: true,
				animationStart: function(current){
					if (window.console && console.log) {
						// example return of current slide number
						console.log('animationStart on slide: ', current);
					};
				},
				animationComplete: function(current){
					if (window.console && console.log) {
						// example return of current slide number
						console.log('animationComplete on slide: ', current);
					};
				},
				slidesLoaded: function() {
				}
		});
    });

</script>

<!--
<style type="text/css">
td img {display: block;}td img {display: block;}
</style>
-->

</head>

<body>
<div class="page_container">
    <div class="header">
    	<div class="login_info">
        	<ul>
            	<li id="register_link"><a href="parents/">Register</a></li>
                <li id="login_link"><a href="login.php">Login</a></li>
	            <li id="pay_link"><a href="https://www.paulthetutors.com/ccpay/">Pay your bill</a></li>
                <li id="start_link"><a href="start.php">Get Started</a></li>
            </ul>
        </div>
    	<div class="logo_container">
            <a href="http://www.paulthetutors.com"><img src="/includes/images/logo.png" alt="Paul the Tutor's Education Center Logo" class="logo"></a>
            <span class="quick_contact_info">
                <p>(510) 730-0390</p>
                <p>4235 Piedmont Ave.</p>
                <p>Oakland, CA 9461</p>
            </span>
        </div>
      <div class="main_menu">
        	<ul>
                <li class="spacer">&nbsp;</li>
            	<li><a href="#">HOME</a></li>
                <li class="spacer">&nbsp;</li>
            	<li><a href="tutoring.php">TUTORING</a>
                	<ul>
                    	<li><a href="mathscience.php">Math and Science</a></li>
                        <li><a href="enghist.php">English and History</a></li>
                        <li><a href="testprep.php">Test Prep</a></li>
                    </ul>
                </li>
                <li class="spacer">&nbsp;</li>
                <li><a href="testprep.php">TEST PREP</a>
                	<ul>
                    	<li><a href="satprep.php">SAT Prep</a></li>
                        <li><a href="actprep.php">ACT Prep</a></li>
                        <li><a href="hsex.php">SSAT/ISEE/HSPT</a></li>
                    </ul>
                </li>
                <li class="spacer">&nbsp;</li>
                <li><a href="ld.php">LOCATIONS</a>                
                	<ul>
                    	<li><a href="piedmont.php">Piedmont</a></li>
                        <li><a href="lafayette.php">Berkeley</a></li>
                        <li><a href="san_mateo.php">San Mateo</a></li>
                        <li><a href="berkeley.php">Lafayette</a></li>
                        <li><a href="davis.php">Davis</a></li>
                    </ul>
                </li>
                <li class="spacer">&nbsp;</li>
                <li><a href="ld.php">LEARNING DIFFERENCES</a></li>
                <li class="spacer">&nbsp;</li>
                <li><a href="#">ABOUT US</a>
                	<ul>
                    	<li><a href="paul.php">Paul the Tutor</a></li>
                        <li><a href="tutors.php">The Tutors</a></li>
                        <li><a href="whyus.php">Why Us?</a></li>
                        <li><a href="howitworks.php">How it Works</a></li>
                        <li><a href="locations.php">Locations</a></li>
                        <li><a href="rates.php">Rates</a></li>
                        <li><a href="hours.php">Hours</a></li>
                    </ul>
                </li>
                <li class="spacer">&nbsp;</li>
                <li><a href="contact.php">CONTACT US</a>
                      <ul>
                    	<li><a href="initial_contact.php">Initial Contact</a></li>
                        <li><a href="contact.php">Contact Information</a></li>
                      </ul>         
                </li>
                <li class="spacer">&nbsp;</li>
                <li><a href="get_started.php">GET STARTED</a></li>
				<li class="spacer">&nbsp;</li>
                <li><a href="#">RATES</a></li>
				<li class="spacer">&nbsp;</li>
                <li><a href="#">HOURS</a></li>
                <li class="spacer">&nbsp;</li>
            </ul>
        </div>
        
    </div>
    <div class="main_container">
        <div class="nav_bar">
            <p class="Head2_Green">Locations</p>
            <div id="accordion">      	
            
                <h3 class="accordion_header"><a href="piedmont.htm" class="nav_bar_ac_title">Piedmont - Main</a></h3>
                <div class="accordion_section">
                    <ul>
                        <li>4235 Piedmont Ave.<br />
                          Oakland, CA 94611 (<a href="https://maps.google.com/maps?q=4235+piedmont+ave.+oakland+ca&amp;ie=UTF-8&amp;hq=&amp;hnear=0x80857df6c5ebab8b:0xe0aa769b143fc95d,4235+Piedmont+Ave,+Oakland,+CA+94611&amp;gl=us&amp;ei=AqSJUNOuBpCUigLtrYDoCQ&amp;ved=0CCAQ8gEwAA" target="_blank">map</a>)</li>
                          <li>
                          (510) 730-0390</li>
                      <LI><a href="logistics.php#piedmont">More Information</a></li>
                     </ul>
                </div>
                
                <h3 class="accordion_header"><a href="lafayette.php" class="nav_bar_ac_title">Lafayette</a></h3>
                <div class="accordion_section">
                    <ul>
                        <li>91 Lafayette Circle</li>
                        <li>Lafayette, CA 94549 (<a href="https://maps.google.com/maps?oe=&amp;q=91+Lafayette+cir+lafayette+ca&amp;ie=UTF-8&amp;hq=&amp;hnear=0x8085625affc008b9:0xf56d238c15bdec5e,91+Lafayette+Cir,+Lafayette,+CA+94549&amp;gl=us&amp;ei=l6CJUJDLNIK3iwL8xYEY&amp;ved=0CCQQ8gEwAA" target="_blank">map</a>)</li>
                        <li>(510) 730-0390</li>
                        <li><a href="lafayette.php">More Informaiton</a></li>
                        <li></li>
                    </ul>
                </div>
                
                <h3 class="accordion_header"><a href="berkeley.htm" class="nav_bar_ac_title">Berkeley</a></h3>
                <div class="accordion_section">
                    <ul>
                        <li>Discounted In-Home Tutoring</li>
                        <li>Starting at $65/hr (<a href="rates.php#berkeley">rates</a>) </li>
                      
                        <li>(510) 730-0390</li>
                        <li><a href="berkeley.php">More Information</a></li>
                      
                  </ul>
                </div>

              <h3 class="accordion_header"><a href="pen.htm" class="nav_bar_ac_title">San Mateo</a></h3>
                <div class="accordion_section">
                    <ul>
                        <li>161 W. 25th Ave. #205</li>
                        <li> San Mateo, CA 94403 (<a href="http://maps.google.com/maps?q=161+W.+25th+St.+San+Mateo,+CA+94403&amp;um=1&amp;ie=UTF-8&amp;sa=X&amp;ei=xOUKUZmVDImJiwK6jIDYCg&amp;ved=0CAsQ_AUoAA" target="_blank">map</a>)</li>
                        <li>650-918-0970 </li>
                        <li><a href="peninsula.php">More Information</a></li>
                        <li></li>
                  </ul>
                </div>
                
                <h3 class="accordion_header"><a href="davis.htm" class="nav_bar_ac_title">Davis</a></h3>
                <div class="accordion_section">
                    <ul>
                        <li></li>
                        <li>Special Rate - $40/hr (<a href="logistics.php">rates</a>)</li>
                        <li><a href="davis.php">More Information</a></li>
                        
                    </ul>
                 </div>
                 
                <h3 class="accordion_header"><a href="online.htm" class="nav_bar_ac_title">Online</a></h3>
                <div class="accordion_section">
                    <ul>
                        <li><a href="distance.php">How it Works</a></li>
                        <li></li>
                        <li>Online Rates - $60/hr (<a href="logistics.php">rates</a>)</li>
                     </ul>
                </div>
            </div>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
          <p>
          <hr> 
           <p class="Head2_Green">Testimonials</p>         
         

            <span class="left_bar_test"> <div id="yelp"><a target="_blank" href=http://www.yelp.com/biz/paul-the-tutors-education-center-oakland><img src='/images/yelp-logo.jpg' /><img class='stars' src=http://s3-media1.ak.yelpcdn.com/assets/2/www/img/f1def11e4e79/ico/stars/v1/stars_5.png alt='Yelp 5 Stars' title='Read what people are saying about us on Yelp!' /></a>
          </div> 
          <!--End Yelp Review -->
          <br />
          <p class="BPN"><a href="http://www.google.com/cse?cx=003626926757047839349:pskr98qzpuk&amp;cof=FORID:0&amp;q=%22paul+the+tutor%22&amp;sa=Search+BPN#gsc.tab=0&amp;gsc.q=%22paul%20the%20tutor%22&amp;gsc.page=1" target="_blank">Berkeley Parents Network</a></p>
            <p class="left_bar_test">Read the BPN Love (<a href="http://www.google.com/cse?cx=003626926757047839349:pskr98qzpuk&amp;cof=FORID:0&amp;q=%22paul+the+tutor%22&amp;sa=Search+BPN#gsc.tab=0&amp;gsc.q=%22paul%20the%20tutor%22&amp;gsc.page=1" target="_blank">click here</a>)</p>
                                </span>

          <hr> 
          <br /> <table width="199" border="0" cellpadding="0" cellspacing="0" class="get_started_left" style="display: inline-table;">
  <!-- fwtable fwsrc="get_started.png" fwpage="Page 1" fwbase="get_started.gif" fwstyle="Dreamweaver" fwdocid = "1580965677" fwnested="0" -->
  <tr>
    <td><img src="images/spacer.gif" alt="" name="undefined_2" width="199" height="1" border="0" /></td>
    <td><img src="images/spacer.gif" alt="" name="undefined_2" width="1" height="1" border="0" /></td>
  </tr>
  <tr>
    <td><img name="get_started_r1_c1" src="images/get_started_r1_c1.gif" width="199" height="86" border="0" id="get_started_r1_c1" usemap="#m_get_started_r1_c1" alt="" /></td>
    <td><img src="images/spacer.gif" alt="" name="undefined_2" width="1" height="86" border="0" /></td>
  </tr>
  <tr>
    <td><img name="get_started_r2_c1" src="images/get_started_r2_c1.gif" width="199" height="10" border="0" id="get_started_r2_c1" alt="" /></td>
    <td><img src="images/spacer.gif" alt="" name="undefined_2" width="1" height="10" border="0" /></td>
  </tr>
</table>
<map name="m_get_started_r1_c1" id="m_get_started_r1_c1">
  <area shape="poly" coords="1,0,0,57,117,59,141,86,164,83,163,58,199,56,198,2,198,2" href="get_started.php" alt="" />
</map>

<p>&nbsp;</p>
        </div>

<? if($other[maincss])
       echo " <div class=\"main_content\"> ";
        
 } // end put_header_2013

/***********************************************************************
funtion put footer
***********************************************************************/
function put_footer_2013($popup=0, $other=""){
	if($other[maincss])
		echo "</div>";

?>
  
    <div class="footer">
    	<div class="motto_container">
        	<q id="tutoring">Since 1991</q><q>Not just better grades... better thinkers</q>
        </div>
        <div><a href="#">privacy policy</a> &nbsp;- &nbsp;
        	<a href="#">contact us</a> &nbsp;- &nbsp;
            <a href="#">cancelation/return policy</a> 
        </div>
    </div>
</div>
</body>
</html>

<?

} // End put_footer_2013

/***********************************************************************
funtion put header for paulthetutors.com
***********************************************************************/
function put_ptts_header_old($page_title, $strAbsPath, $folder, $other2){
  
  
  //checks for connection and adds analytics
  MySQL_PaulTheTutor_Connect();
  analytics();
  
  global $strAbsPath;
if (isEmpty($page_title)) $page_title = "Paul the Tutor's Education Center";
$folder  = getfolder("","","");
// get_top_links gets the links which will be used for the links in the top bar.
$arlinks = get_top_links($folder);
?>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="google-site-verification" content="unawIL1y5LuUsTZ1mQiUnNzCruL_L1mktNdyqCjBQIg" />
  <meta http-equiv="pragma" content="no-cache">
        <meta name="keywords" content="Tutoring, LD tutoring, Learning Disability, Learning Disability SAT, LD SAT, SAT, SAT Prep, LD SAT Prep, LD Test Prep, LD SAT Tutoring" />
  <title><?=$page_title;?></title>
  <?php if ($folder == 'admin')?>
  <link href="<?php echo MAIN_BASE_PATH?>/includes/paulthetutors.css" rel="stylesheet" type="text/css" />
  <script language="JavaScript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/gen_validatorv2.js" type="text/javascript"></script>
  <script language="JavaScript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/utils.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery-ui-1.8.4.custom.css"/>
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery-1.7.1.min.js"></script>
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery-ui-1.8.4.custom.min.js"></script>
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery.timeentry.min.js"></script>
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery.ui.timepicker_1.2.js"></script>  

  </head>
  <body>
  <?php if ($other2!='popup'){?>
  <table width="876" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
    <td align="left" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
  <!--Banner-->    <?php if ($other2!='no_banner'){?>
    <tr>
    <td align="right" valign="top" class="header_bg"><a id="logo-link" href="/"></a>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
    <td height="28" align="right" valign="top"></td>
    </tr>
    <tr>
    <td align="right" valign="top" class="header_right_txt">(510) 730-0390<br />
  4235 Piedmont Ave.<br />
  Oakland, CA 94611</td>
    </tr>
  </table>
  </td>
    </tr>
  <!--Banner-->

  <!--Menu-->  
    <tr>
    <td align="left" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
<?
// put the actual links into the top bar    
for($i=1;$i<8;$i++){ 
?>
     
     <td width="107" align="left" valign="top" class="Services"><a href="<?=$arlinks[$i][0];?>"><?=$arlinks[$i][1];?></a></td>
    <td width="4" align="left" valign="top" style="width:4px;"><img src="<?php echo MAIN_BASE_PATH?>/images/navi_space.jpg" alt="space" /></td>

	<? //generate_navbar( $arlinks ); ?>

<?
} // ends the for loop
?>
     <td width="107" align="left" valign="top" class="Services"><a href="<?=$arlinks[$i][0];?>"><?=$arlinks[$i][1];?></a></td>
    </tr>
  </table></td>
    </tr>
  <!--Menu-->     
    <?}?>  
    <tr>
    <td height="10" align="left" valign="top">
    </td>
    </tr>

  <tr>
  <td valign="top">
  <?php } else { ?>
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr><td align="right">
    &nbsp;&nbsp;<button onClick="popup_close()">Close</button>
</td></tr>
<? } // end else ?>
<tr>
    <td align="left" valign="top">
<?
} //end put header

/***********************************************************************
funtion put footer
***********************************************************************/
function put_ptts_footer_old($other){
?>  
  </td></tr>
   <tr>
    <td height="5" align="left" valign="top"></td>
    </tr>
<?
if ($other!='popup'){
?>
  <!--Footer-->  
    <tr>
    <td align="center" valign="top" class="footer_bg"><table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr>
    <td align="right" valign="top" class="footer_left_txt">Not Just Better Grades... Better Thinkers</td>
    <td width="30" align="center" valign="top">&nbsp;</td>
    <td width="300" align="right" valign="middle" class="footer_txt">&copy; 2010 Paul The Tutor's Education Center</td>
    </tr>
  </table></td>
    </tr>
 
    <tr>
    <td align="center" valign="top"> <span class="footer_txt"><a href="privacy.php" target="_blank">privacy policy</a> | <a href="contact.php">contact us</a> | <a href="cancpolicy.php" target="_blank">cancelation/return policy</a> </span></td>
    </tr>
  </table>
    <!--Footer-->   
<? } else {?>
&nbsp;&nbsp;<td align="right"><button onClick="popup_close()">Close</button>


<? }?> 
  </td>
    </tr>
  </table>
  </body>
  </html>
<?
} // end put_ptts_footer

/***********************************************************************
funtion put header for paulthetutors.com 2014
***********************************************************************/
function put_header_2014($page_title="Paul the Tutor's Education Center", $strBack=NULL, $folder=NULL,$other=NULL){
	useHTTPS();

	//checks for connection and adds analytics
 	MySQL_PaulTheTutor_Connect();
  	analytics();
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="google-site-verification" content="unawIL1y5LuUsTZ1mQiUnNzCruL_L1mktNdyqCjBQIg" />
<meta http-equiv="pragma" content="no-cache" />
<meta name="keywords" content="Tutoring, LD tutoring, Learning Disability, Learning Disability SAT, LD SAT, SAT, SAT Prep, LD SAT Prep, LD Test Prep, LD SAT Tutoring" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$page_title;?></title>
<link href="/includes/css_files/styles_main_2014.css" rel="stylesheet" type="text/css" />
<link href="/includes/css_files/styles_beta.css" rel="stylesheet" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script src="/includes/js_files/slides.min.jquery.js"></script>
<!--- Sandips code begin-->
<script type="text/javascript">

function saveupdt(field,id,tablename)
{
var str = field+ "_input_" +  id;
var changetext=$("#"+str).val();
var input_texts=  field + "_text_" +  id;
var fieldid = 'updt_'+ field + '_' + id;
var dispfld = 'edit_'+ field + '_' + id;
if(changetext.length>0)
{
$.ajax({
type: "POST",
async:false,
url: "https://www.paulthetutors.com/includes/php_files/table_edit_ajax.php",
data: {id:id,tablename:tablename,fieldname:field,fieldvalue:changetext},
cache: false,
success: function(response)
{
$("#"+input_texts).text(response);
$("#"+input_texts).show();
$("#"+dispfld).show();
$("#"+str).hide();
$("#"+ fieldid).hide();
} ,
error: function(data)
{//$("#"+input_texts).html(changetext);
 alert('The data is error ' + data) ;
}
});
}
else
{ alert('Enter something');
}
};


function fieldHide(field,id)
{

var str = field + "_text_" + id;
var res = field;
var search_str = "_text_" +  id;
var text_str =  field +   "_input_" + id;
var fieldid = 'updt_'+ res + '_' + id;
var dispfld = 'edit_'+ res + '_' + id;
//alert ('value is now' + res);
$("#"+text_str).show();
$("#"+str).hide();
$("#"+dispfld).hide();
$("#"+ fieldid).show();
};
// Edit input box click action
$(".editbox").keyup(function()
{
return false ;
});
// Outside click action



</script>
    <!--Sandips code end-->

<?php //if($folder != '') { ?>
  <!-- <link href="<?php //echo MAIN_BASE_PATH?>/includes/paulthetutors.css" rel="stylesheet" type="text/css" /> -->
<?php //} ?>

  <script language="JavaScript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/gen_validatorv2.js" type="text/javascript"></script>
  <script language="JavaScript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/utils.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery-ui-1.8.4.custom.css"/>
  <!--
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery-1.7.1.min.js"></script>
  -->
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery-ui-1.8.4.custom.min.js"></script>
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery.timeentry.min.js"></scrip>
  <script type="text/javascript" src="<?php echo MAIN_BASE_PATH?>/includes/js_files/jquery.ui.timepicker_1.2.js"></script>

<?php if( $other != "popup" ):  ?>

<style type="text/css">
  /** some pages have tables with widths=800px, this overwrites
  those styles and makes sure the table fits in the page**/
  table {
    max-width: 960px !important;
  	margin: 0 auto;
  }
</style>

<style type="text/css">
/*causes problems for action uttons in comments page*/
/*td img {display: block;}td img {display: block;}*/
</style>

</head>

<body>
<div class="page_container">
    <div class="header">

    	<div class="logo_container">

     	<?php 
    
    	$url = $_SERVER['REQUEST_URI'];

     	if( strpos( $url, "admin" ) || strpos( $url, "tutors" ) || strpos( $url, "parents" ) ||
		  	strpos( $url, "ldsatadmin" ) || strpos( $url, "students" ) ) { ?>

		  	<link href="<?php echo MAIN_BASE_PATH?>/includes/paulthetutors.css" rel="stylesheet" type="text/css" />

            <a href="http://www.paulthetutors.com">
            	<img src="/includes/images/logo.png" 
            	alt="Paul the Tutor's Education Center Logo" 
            	class="logo" style="margin-top: 0">
            </a>   

    	<?php } else { ?>
 
            <div class="login_info">
	        	<ul>
	            	<li id="register_link"><a href="parents/fam_register.php">Register</a></li>
	                <li id="login_link"><a href="login.php">Login</a></li>
		            <li id="pay_link"><a href="https://www.paulthetutors.com/ccpay/">Pay your bill</a></li>
	                <li id="start_link"><a href="contact.php">Get Started</a></li>
	            </ul>
	        </div>

            <a href="http://www.paulthetutors.com"><img src="/includes/images/logo.png" alt="Paul the Tutor's Education Center Logo" class="logo"></a>
        
<!--             <span class="quick_contact_info">
                <p>(510) 730-0390</p>
                <p>4235 Piedmont Ave.</p>
                <p>Oakland, CA 9461</p>
            </span>	 -->	

    	<?php } ?>
    	
        </div>

        <!-- NAVBAR start -->
      <div class="main_menu">

          <?php 
		  $folder = getfolder("","","");
          $links = get_top_links2( $folder ); 

          if( $folder == "admin" || $folder == "tutors" || $folder == "parents" || 
          		$folder == "students" || $folder == "ldsatadmin" ) {
          ?>

          <style type="text/css">
          	body {
				float: left;
				margin: 0 0 0 5px !important;
          	}
          </style>

          <?

          } 
          
          generate_navbar( $links ); ?>

      </div>
      <!-- NAVBAR end -->
        
    </div>
        <div class="main_container">

        <?php if( $page_title == "Paul the Tutor's Education Center Home" ): ?>

        <div class="nav_bar" style="width: 150px;" >

        	<div class="sidebar_container">
	            <p class="Head1_Brown">Locations</p>
	            <div id="accordion">      	
	            
	                <h3 class="accordion_header"><a href="location.php?id=1" class="nav_bar_ac_title">Piedmont - Main</a></h3>
	                <div class="accordion_section">
	                    <ul>
	                        <li>4235 Piedmont Ave.<br />
	                          Oakland, CA 94611 (<a href="https://maps.google.com/maps?q=4235+piedmont+ave.+oakland+ca&amp;ie=UTF-8&amp;hq=&amp;hnear=0x80857df6c5ebab8b:0xe0aa769b143fc95d,4235+Piedmont+Ave,+Oakland,+CA+94611&amp;gl=us&amp;ei=AqSJUNOuBpCUigLtrYDoCQ&amp;ved=0CCAQ8gEwAA" target="_blank">map</a>)</li>
	                          <li>
	                          (510) 730-0390</li>
	                      <LI><a href="logistics.php#piedmont">More Information</a></li>
	                     </ul>
	                </div>
	                
	                <h3 class="accordion_header"><a href="location.php?id=4" class="nav_bar_ac_title">Lafayette</a></h3>
	                <div class="accordion_section">
	                    <ul>
	                        <li>91 Lafayette Circle</li>
	                        <li>Lafayette, CA 94549 (<a href="https://maps.google.com/maps?oe=&amp;q=91+Lafayette+cir+lafayette+ca&amp;ie=UTF-8&amp;hq=&amp;hnear=0x8085625affc008b9:0xf56d238c15bdec5e,91+Lafayette+Cir,+Lafayette,+CA+94549&amp;gl=us&amp;ei=l6CJUJDLNIK3iwL8xYEY&amp;ved=0CCQQ8gEwAA" target="_blank">map</a>)</li>
	                        <li>(510) 730-0390</li>
	                        <li><a href="location.php?id=4">More Informaiton</a></li>
	                        <li></li>
	                    </ul>
	                </div>
	                
	                <h3 class="accordion_header"><a href="location.php?id=9" class="nav_bar_ac_title">Berkeley</a></h3>
	                <div class="accordion_section">
	                    <ul>
	                        <li>Discounted In-Home Tutoring</li>
	                        <li>Starting at $65/hr (<a href="rates.php#berkeley">rates</a>) </li>
	                      
	                        <li>(510) 730-0390</li>
	                        <li><a href="location.php?id=9">More Information</a></li>
	                      
	                  </ul>
	                </div>

	              <h3 class="accordion_header"><a href="location.php?id=5" class="nav_bar_ac_title">San Mateo</a></h3>
	                <div class="accordion_section">
	                    <ul>
	                        <li>161 W. 25th Ave. #205</li>
	                        <li> San Mateo, CA 94403 (<a href="http://maps.google.com/maps?q=161+W.+25th+St.+San+Mateo,+CA+94403&amp;um=1&amp;ie=UTF-8&amp;sa=X&amp;ei=xOUKUZmVDImJiwK6jIDYCg&amp;ved=0CAsQ_AUoAA" target="_blank">map</a>)</li>
	                        <li>650-918-0970 </li>
	                        <li><a href="location.php?id=5">More Information</a></li>
	                        <li></li>
	                  </ul>
	                </div>
	                
	                <h3 class="accordion_header"><a href="/location.php?id=8" class="nav_bar_ac_title">Davis</a></h3>
	                <div class="accordion_section">
	                    <ul>
	                        <li></li>
	                        <li>Special Rate - $40/hr (<a href="logistics.php">rates</a>)</li>
	                        <li><a href="/location.php?id=8">More Information</a></li>
	                        
	                    </ul>
	                 </div>
	                 
	                <h3 class="accordion_header"><a href="distance.php" class="nav_bar_ac_title">Online</a></h3>
	                <div class="accordion_section">
	                    <ul>
	                        <li><a href="distance.php">How it Works</a></li>
	                        <li></li>
	                        <li>Online Rates - $60/hr (<a href="logistics.php">rates</a>)</li>
	                     </ul>
	                </div>
	            </div>
	        </div>
	        <p>&nbsp;</p>
	        <p>&nbsp;</p>

			<div class="sidebar_container">
	          	<p class="Head1_Brown">Web Love</p>       

	            <span class="left_bar_test"> 

	            	<div id="bronzeStar"> 
	            	
	            		<a href="http://www.parentspress.com/Best-of-Parents-Press?additionalinfo=Best+Tutorial+Programs">
	                  		<img src="includes/images/slides/bronze_star.png" height="25" width="25">
	                  		<img src="includes/images/pp-newlogo.png" height="25" width="100">
	                  		<p>Best of the East Bay 2014</p>
	            		</a> 
	            	
	            	</div>

	            	<hr>

	            	<div id="yelp"><a target="_blank" href=http://www.yelp.com/biz/paul-the-tutors-education-center-oakland><img src='/images/yelp-logo.jpg' /><img class='stars' src=http://s3-media1.ak.yelpcdn.com/assets/2/www/img/f1def11e4e79/ico/stars/v1/stars_5.png alt='Yelp 5 Stars' title='Read what people are saying about us on Yelp!' /></a>
	          		</div> 
	          
	          		<hr>

	          <!--End Yelp Review -->
	          <br />
	          <p class="BPN"><a href="http://www.google.com/cse?cx=003626926757047839349:pskr98qzpuk&amp;cof=FORID:0&amp;q=%22paul+the+tutor%22&amp;sa=Search+BPN#gsc.tab=0&amp;gsc.q=%22paul%20the%20tutor%22&amp;gsc.page=1" target="_blank">Berkeley Parents Network</a></p>
	            <p class="left_bar_test">
	              <a href="http://www.google.com/cse?cx=003626926757047839349:pskr98qzpuk&amp;cof=FORID:0&amp;q=%22paul+the+tutor%22&amp;sa=Search+BPN#gsc.tab=0&amp;gsc.q=%22paul%20the%20tutor%22&amp;gsc.page=1" target="_blank">Read the BPN Love </a></p>
	                                </span>
	          <br /> 

				<p>&nbsp;</p>
			</div>
        </div>

    <?php else: ?>

		<div class="content_wrapper">

	<?php endif; ?>

<?php else: //close button for pop ups ?>

    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
	<!-- Extra code added by Sandip to hide the close button on a invoice pop up 10/23/14 Issue # 1 on Webbit -->
    <tr><td><?php 
 	if (strpos((basename($_SERVER['PHP_SELF'])),'invoice_printable') === false) { ?>	
    &nbsp;&nbsp;<button onClick="popup_close()">Close</button>
    <!-- Extra code added by Sandip- End--> 
<?php } 
      endif; ?>

<? } // end put_header_2014

/***********************************************************************
funtion put footer
***********************************************************************/
function put_footer_2014($other="not pop up") {
?>  
    </div> <!-- end .main_content -->
  </div> <!-- end .main_container -->

  <!-- Footer 2014-->
  </td></tr>
   <tr>
    <td height="5" align="left" valign="top"></td>
    </tr>
<?
if ($other!='popup'){
?>
	<!-- some pages have open tables -->
	</table></td></table>

  <!--Footer-->  
    <div class="footer">
      <div class="motto_container">
          <q id="tutoring">Since 1991</q><q>Not just better grades... better thinkers</q>
        </div>
        <div>
        	
        	<a href="contact.php">privacy policy</a> &nbsp;- &nbsp;
            <a href="parents/fam_register.php">register</a> &nbsp;- &nbsp;
          	<a href="contact.php">contact us</a> &nbsp;- &nbsp;
            <a href="contact.php">cancelation/return policy</a> 

        </div>
    </div>
    <!--Footer-->   

<? } else { //yet another close button for popups 
if (strpos((basename($_SERVER['PHP_SELF'])),'invoice_printable') === false) { 	
    
?>

&nbsp;&nbsp;<td align="right"><button onClick="popup_close()">Close</button>

<? }}?> 
  </td>
    </tr>
  </table>
  </body>
  </html>
<?
} // end put_footer_2014

/***********************************************************************
funtion put_ptts_header directs request to header funtions depending on domain
***********************************************************************/
function put_ptts_header($page_title="Paul the Tutor's Education Center", $strBack=NULL, $folder=NULL,$other=NULL) {
	$url = $_SERVER['REQUEST_URI'];

	put_header_2014( $page_title, $strBack, $folder, $other );
	return;
	if( /**strpos( $url, "admin" ) || strpos( $url, "tutors" ) || strpos( $url, "parents" ) || 
		 *strpos( $url, "ccpay" ) || **/ strpos( $url, "ldsatadmin" ) /**|| strpos( $url, "students" )**/ ) {

		put_ptts_header_old( $page_title, $strBack, $folder, $other );

	} else {

		put_header_2014( $page_title, $strBack, $folder, $other );

	}
}


/***********************************************************************
funtion put_ptts_footer directs request to header funtions depending on domain
***********************************************************************/
function put_ptts_footer($other=NULL) {
	$url = $_SERVER['REQUEST_URI'];

	put_footer_2014( $other );
	return;
	if( /**strpos( $url, "admin" ) || strpos( $url, "tutors" ) ||  strpos( $url, "parents" ) ||  
		*strpos( $url, "ccpay" ) || **/strpos( $url, "ldsatadmin" ) /**|| strpos( $url, "students" )**/ ) {

		put_ptts_footer_old( $other );

	} else {

		put_footer_2014( $other );


	}
}


/***********************************************************************
funtion get_tut_info($tutor_id)
inputs: tutors id
outputs: array with all of tutors info
**********************************************************************/
function get_tut_info($tutor_id){
  // $TQStr = "select * from PT_Tutors where id = $tutor_id";
  // $TRS = runquery($TQStr);
  // $TAR = mysql_fetch_array($TRS);
  // return $TAR;
	$url = $_SERVER['REQUEST_URI'];
	mail_alert('mtandemeskel@gmail.com', "get_tut_info" , "url is $url", 'del');
	return tutor_info( $tutor_id );
} // end get_tut_info

/***********************************************************************
funtion get_fam_name($fam_id)
inputs: family id
outputs: main_name (students) as a string
***********************************************************************/
function get_fam_name($fam_id){
  $FQStr = "select main_name from PT_Family_Info where id = $fam_id";
  $FRS = runquery($FQStr);
  $far = mysql_fetch_array($FRS);
  $students = get_family_snames($fam_id);
  
  $fn_str = "$far[main_name] ($students)";
  return $fn_str;
} // end get_fam_name

/****************************************************
 * puts row to get tutor's id
 * inputs: pre-selected tutor is, name of field, code to execute onchange (optional)
 * ***************************************************/
function get_employee_id($label=NULL, $field_name="employee_id", $selected_value, $employee_type=NULL, $opts=null, $callback=""){
	if(isEmpty($label)) $label = "Choose Employee";
?>
   <tr valign="middle"><td><div align="right"><?=$label;?>
<? if((isset($opts['required']) && $opts['required'])){  ?>
<font color=#FF0000">*</font> 

<?  }  ?>
   &nbsp;</td><td>
<?  

	$opts['type'] = 'employee';
  tutorsid_menu($selected_value, $field_name, $callback, $opts);
  echo "</td><tr>";
}  

/****************************************************
 * puts row to get tutor's id
 * inputs: pre-selected tutor is, name of field, code to execute onchange (optional)
 * ***************************************************/
function get_tutor_id($selected_value, $name="tid", $callback="", $opts=null,$label=NULL){
	if(isEmpty($label)) $label = "Tutor";
?>
   <tr valign="middle"><td><div align="right"><?=$label;?>
<? if((isset($opts['required']) and $opts['required'])){  ?>
<font color=#FF0000">*</font> 

<?  }  ?>
   &nbsp;</td><td>
<?    
  tutorsid_menu($selected_value, $name, $callback, $opts);
  echo "</td><tr>";
}  

/****************************************************
 * Show tutors dropdown menu
 * inputs: pre-selected tutor is, name of field, code to execute onchange (optional)
 * ***************************************************/
function tutorsid_menu($selected_value="", $name="tid", $callback="", $opts=null)
{

$where = "WHERE (position LIKE '%tutor%' OR position LIKE '%class%') and archived =0";
$title = "Select A Tutor";

/********Created a check to verify if opts array is populated before checking the contents- sandip 09/22/14**********
/*if($opts['type'] == 'employee')*/
if(isset($opts['type']) && $opts['type'] == 'employee'){
 /***************End Of Updated Code****************/   
	$where = "WHERE (position LIKE '%tutor%' OR position LIKE '%admin%') and archived = 0";
	$title = "Select An Employee";
}
	

if(isset($opts['all']) && $opts['all'] == 1) {
	$title = "Select Employee ";
  $where = '';
} 


if($callback == "Submit")
	$callback = "submit()";

  ?>
  <select id="tutor_menu_<?=$name?>" name="<?=$name?>" onChange="<?=$callback?>">
         <option value=""> <?=$title;?> </option>
       <?
$QStrsi = "select id, first_name, last_name, id from PT_Tutors $where ORDER BY first_name";
if(!($siRS = mysql_query($QStrsi))){
  echo "QStr:  $QStrsi <BR>" . mysql_error() . "<BR><BR>";
}
// if we can not select all
if($opts['just_one'] <> 1){
?>       <option value="0"> All </option>
<? 
}

while($arsi = mysql_fetch_array($siRS)){
  $sel_str = $arsi['first_name']." ".$arsi['last_name'];
?>
       <option value="<?=$arsi['id']?>" <?=$selected_value==$arsi['id']?"Selected":"";?>><?=$sel_str?></option>
<? } ?>
       
       <option value="-1"> Other </option>
	   
	    </select>
  <?
} // end tutid_menu
     
/****************************************************
 * puts a 2 columns to get student id
 * inputs: pre-selected student is, name of field, code to execute onchange (optional)
 * ***************************************************/
    
     
function get_student_id($selected_value=NULL, $field_name="student_id", $callback="", $opts=null, $first_label="Select A Student"){
	put_student_search ("drop", $field_name, $selected_value, $first_label , $callback);

}

/****************************************************
 * puts a 2 columns to get student id
 * inputs: pre-selected student is, name of field, code to execute onchange (optional)
 * ***************************************************/
    
     
function get_student_id_old($selected_value=NULL, $name="student_id", $callback="", $opts=null, $first_label="Select A Student"){

?>
   <tr valign="middle"><td><div align="right">Student
<? if($opts['required'] == 1) echo"<font color=\"#FF0000\">*</font>"; ?>
   &nbsp;</td><td>
<?    
  studentid_menu($selected_value, $name, $callback, $opts, $first_label);
  echo "</td><tr>";
}  

/****************************************************
 * calls student search function
 * inputs: pre-selected tutor is, name of field, code to execute onchange (optional)
 * ***************************************************/
function studentid_menu_p($selected_value=NULL, $field_name="student_id", $callback="", $opts=null, $first_label="Select A Student")
{
	just_student_search("drop", $field_name,  $selected_value, "Student Info", $callback);
}
/****************************************************
 * Show students dropdown menu
 * inputs: pre-selected tutor is, name of field, code to execute onchange (optional)
 * ***************************************************/
function studentid_menu_old($selected_value=NULL, $name="student_id", $callback="", $opts=null, $first_label="Select A Student")
{
  !$opts && $opts=array();
   
  
  ?>
  <select id="student_menu_<?=$name?>" name="<?=$name;?>" onChange="<?=$callback?>">
         <option value=""><?=$first_label;?></option>
       <?
 
	   
	   
if(isset($opts['all']) && $opts['all']) {
  $where = '';
} else {
    //  if we don't want all of the students;
}
$QStrsi = "select id, first_name, last_name, id from PTStudentInfo_New $where ORDER BY first_name,last_name DESC";
if(!($siRS = mysql_query($QStrsi))){
  echo "QStr:  $QStrsi <BR>" . mysql_error() . "<BR><BR>";
}

$arsis[0] = "All";
while($arsi = mysql_fetch_array($siRS)){
  $sel_str = $arsi['first_name']." ".$arsi['last_name'];
?>
       <option value="<?=$arsi['id']?>" <?=$selected_value==$arsi['id']?"Selected":"";?>><?=$sel_str?></option>
<? } ?>

       <option value="-1"> Other </option>
  

        </select>
  <?
} // end studentid_menu
     
     
     

/***********************************************************************
funtion fam_menu($style, $name, $fam_id, $label, $other)
inputs: style(student or last); $inputname = the name of the select; 
$fam_id = the selected option; 
$label = the label of the first option
outputs: a pull down menu for selecting a family
***********************************************************************/
function fam_menu($style="student", $inputname="sid", $fam_id=0, $label="", $other=""){
if ($other != "archive")
  $table = "PT_Family_Info";
else
  $table = "ZZ_PT_Family_Info_Old";
$FRS = runquery("select ".($other!='archive' ? 'id' : 'old_id')." as id, main_name, students from $table ".($style == "student" ? "ORDER BY students" : ""));
if ($style == "student"){
  while ($far = mysql_fetch_array($FRS)){
     $lab_id = $far['id']; 
     $arr[$far['id']] =  "$far[main_name] ($lab_id) ($far[students])";
  }
}elseif($style == "last"){
  while ($far = mysql_fetch_array($FRS)){
    $name = ""; $a = array();
    $a = explode(" ", trim($far['main_name']));
    $a = array_reverse($a);
    foreach ($a as $m=>$n){
      if ($a!='')
        $name.= trim($n).($m == 0 ? ", " : "");
    }
    $lab_id = $far['id']; 
    $arr[$far['id']] = "$name ($far[students]) ($lab_id)";
  }
  natcasesort ($arr);
}

if ($other == "return_fam_name")
  return $arr[$fam_id];
!isset($ret) && $ret = '';
$ret.='<select name="'.$inputname.'" id="'.$inputname.'">
      <option value="" selected>'.$label.'</option>';

foreach ($arr as $k=>$v){
  $ret.='<option value="'.$k.'" '.($fam_id == $k ? "selected" : "").'>'.$v.'</option>';
}

$ret.= '</select>';
return $ret;

} // end fam_menu

/***********************************************************************
funtion put_fam_menu($style, $name, $fam_id, $label, $other)
inputs: style(student or last); $inputname = the name of the select; $fam_id = the selected family; $label = the label of the first option
outputs: none
objective: display family menu
***********************************************************************/
function put_fam_menu($style="drop", $inputname="fid", $fam_id=0, $label="", $other=""){
// used to simply call a function that put a drop down menu. Now calls a function that has a search and drop down.
  $ret = fam_menu($style, $inputname, $fam_id, $label, $other);
  echo $ret;

// put_fam_search ("drop", $field_name="fid", $fam_id=0, $label="", $callback="");


} // end fam_menu

/***********************************************************************
funtion class_menu()
$class_id = this is the class that is already selected.


***********************************************************************/
function class_menu(){
	SelectFromQuery($QStr, $disName, $varName, $disArray, $varSelected, $strComment, $special, $labelFirst);
}	

/***********************************************************************
funtion reqToVars()
inputs: none
outputs: none
objective: take all variables in $_Request and make them global variables
***********************************************************************/
function reqToVars(){
// echo "In reqtovars Now <BR><BR>";
  foreach($_REQUEST as $key=>$value) { 
    global ${$key}; 
    ${$key} = $value;
  }
reset($_REQUEST);
}



/***********************************************************************
funtion gettutBillInfo()
objective: if it is a month prior to 2011, uses the old billing program
  otherwise used the new one
***********************************************************************/
Function gettutBillInfo($month, $year, $sid, $tid, $other) {
  if($year > 2010){
    $bar = gettutBillInfo_2011($month, $year, $sid, $tid, $other);
  } else {
    $bar = gettutBillInfo_2010($month, $year, $sid, $tid, $other);  
  }
  return $bar;
}

/*-------------------------------------------------------------------  */
/* gets the array with a students billing information for a month  */
/* returns a array with
  arBillInfo[date,rate,hours,special,comments]*/
/*-------------------------------------------------------------------  */
///get the schedule for the students: day of week, hours and rate
Function gettutBillInfo_2011($month, $year, $sid, $tid, $other) {
  $first_of_month = "$year/$month/1";
  if($month <12){
    $next_month = $month + 1;
    $first_of_nextmonth = "$year/$next_month/1";
  } else {
    $next_year = $year + 1;
    $first_of_nextmonth = "$next_year/1/1";
  }  
  $i = 0;
// get the added appts
/*Updated by Sandip on 10/24/14 to accomodate the month null provision*/
//   $QStr = "select a.*, a.name as student_name, l.short_name as location, t.first_name as t_first_name, a.student_id as student_id, t.last_name as t_last_name  from PTAddedApp a LEFT JOIN PT_Tutors t ON a.tid = t.id LEFT JOIN PT_Locations l ON a.location_id = l.id where year(a.date) = $year"." and month(a.date) = $month and (a.sid = $sid)  ".($tid ? "and a.tid = $tid" : ""). " Order by a.date, a.start_time ASC";
   $QStr = "select a.*, a.name as student_name, l.short_name as location, t.first_name as t_first_name, a.student_id as student_id, t.last_name as t_last_name  from PTAddedApp a LEFT JOIN PT_Tutors t ON a.tid = t.id LEFT JOIN PT_Locations l ON a.location_id = l.id where year(a.date) = $year ".($month ? " and month(a.date) = $month" : ""). " and (a.sid = $sid)  ".($tid ? "and a.tid = $tid" : ""). " Order by a.date, a.start_time ASC";   
   
//End Of code changes**//   

// echo "QStr is $QStr <BR>";  
  if(!($AdARS = mysql_query($QStr))){
    echo "$QStr <br>" . mysql_error();
  } else {
//printRS($AdARS);
  }  
// echo $QStr . "qstr <BR>";  
        $arBillInfo = null;
  while($arAdA = mysql_fetch_array($AdARS)){
// printarray($arAdA);
    $arDate = explode("-", $arAdA['date']);
// echo "i is $i <BR>";
    $arBillInfo[$i]['student_name'] = $arAdA['student_name'];
    $arBillInfo[$i]['printday'] = $arDate[2];
    $arBillInfo[$i]['date'] = date("dS \of M", mktime (0,0,0,$arDate[1],$arDate[2],$arDate[0]));
    $arBillInfo[$i]['special'] = "&nbsp;";
    $arBillInfo[$i]['comments'] = $arAdA['comments'];
    $arBillInfo[$i]['location'] = ($arAdA['location']? $arAdA['location'] : "None");
    $arBillInfo[$i]['start_time'] = $arAdA['start_time'];
    $arBillInfo[$i]['id'] = $arAdA['id'];
    $arBillInfo[$i]['tid'] = $arAdA['tid'];
    $arBillInfo[$i]['t_name'] = $arAdA['t_first_name']." ".strtoupper(substr($arAdA['t_last_name'],0,1));
    $arBillInfo[$i]['pay'] = $arAdA['pay'];
    $arBillInfo[$i]['hours'] = $arAdA['hours'];
    $arBillInfo[$i]['rate'] = $arAdA['rate'];
    $arBillInfo[$i]['student_id'] = $arAdA['student_id'];
    $i = $i+1;
  }
// printarray($arBillInfo);  
return $arBillInfo;
} //END FUNCTION 

/*-------------------------------------------------------------------  */
/* prints a Roster with the fields provided.                */
/*  strFields is the fields that will be in the table           */
// $arFields is array with key = field and value = Column Title
// $arColumn has the names of columns if specified
// 
/*-------------------------------------------------------------------  */
function tableview($strTable, $strFields, $arColumn, $strRestrictions, $booledit, $sortby, $sortorder, $tableclass, $other){
// printarray($_SESSION);
// if $strFields is blank, fill it with main_fields from PT_Table_Info
if(isEmpty($strFields)){
  $FQStr = "select main_fields from PT_Table_Info where name = '$strTable'";
  $strFields = singlequery($FQStr);
  // if there is nothing listed as columns to show for that table, show all of them
  if(isEmpty($strFields)){
    $strFields = "*";
  }
}

$_SESSION[strTable] = $strTable;
// get's name of the page
$page_name = $_SERVER['PHP_SELF'];
$arPage = explode("/",$page_name);
$numSlash = substr_count("$page_name", "/");
$page_name = $arPage[$numSlash];
// echo $page_name;  
//if the order is indicated, create an oderby statement
if(!(isEmpty($sortby))){
  $orderby = "order by $sortby";
  //if the order is indicated, also include that in the orderby statment
  if(!(isEmpty($sortorder))){
    $orderby = $orderby . " " . $sortorder;
  }
}  
?>
<table class="l_style" border="0" cellspacing="0" cellpadding="4" class=<?=tableclass;?>><tr> 
<?
if(isEmpty($strRestrictions)) $strRestrictions = "1 = 1";
// get the information from the table
// make sure the id is in the search
$strFields = $strFields . ", id as hidden_id";
$QStr = "select $strFields from $strTable where $strRestrictions $orderby ";
$tempRS = runquery($QStr);
$temparray = mysql_fetch_assoc($tempRS);
// while loop will put the titles for every field
while(list($key,$value ) = each($temparray)){
  if($key <> "hidden_id"){ // don't show the hidden id number
  // If the name for a column is set, use it, otherwise, use the function which maipulates names 
      if(isset($arFieldNames[$key])){
        $disName = $arFieldNames[$key];
      } else {
        $disName = setDisplayFieldVals($key);
      } ?>
      <th style="white-space: nowrap">
        <?=$disName;?>
      <a href='<?=$page_name;?>?strTable=<?=$strTable;?>&sortby=<?=$key;?>&sortorder=DESC'>&darr;</a><a href='<?=$page_name;?>?strTable=<?=$strTable;?>&sortby=<?=$key;?>&sortorder=ASC'>&uarr;</a>
      </th>
      <?
    } else {// if  Hidden_id store it
      $hidden_id = $value;
    }  
} //while
    if($booledit == "view" or $booledit == "edit" or $booledit == "full") echo "<th> Action </th></tr>";
  reset($temparray); // go back to the beginning of the array
  do{ // cycle through each row in the table
    echo "<TR>";
    while(list($key,$value ) = each($temparray)){ //print each value from each cell in the row
      if($key <> "hidden_id" ){
        if(isEmpty($value)) $value = "&nbsp;";
        If (strlen($value) >= 50){
          $value = substr($value,0,50);
          $value = $value . "... [truncated]";
        }

		// if the variable is a time, convert it
		$is_time = substr_count($key, 'time');		
		if($is_time > 0) {
			$value = format_time_print($value);
		}	

		// if the field is a date, format it
		$is_date = substr_count($key, 'date');		
		if($is_date > 0) {
			$value = format_date_print($value);
		}	       
	   



        echo "<TD align=\"center\">$value</TD>   ";
      } else {// if  Hidden_id store it
        $hidden_id = $value;
      }  
    } 
    if($booledit == "view" or $booledit == "edit" or $booledit == "full") {
      ?>
<td align=\"center\" >
<? if($booledit == "view" or $booledit == "edit" or $booledit == "full") { // if the user has right to view, edit or delete      
?>    
  <a onClick="javascript:popup('show_record.php?strTable=<?=$strTable;?>&record_id=<?=$hidden_id;?>','Details','600','820')">
      <img src="../images/view.gif" border="0"></a> &nbsp;
<? if($booledit == "edit" or $booledit == "full") { // if the user has right to edit      
?>  
  <a onClick="javascript:popup('edit_record.php?id=<?=$hidden_id;?>&strTable=<?=$strTable;?>','Details','600','820')">
      <img src="../images/edit_pencil.gif" width="16" height="14" border="0"> </a>
<!-- &nbsp;&nbsp;<img src="../images/del_x.gif" width="13" height="13"></td></tr> -->
      <?
    } // end if can see or edit  
        } // end if can edit  
      }
  } while($temparray = mysql_fetch_assoc($tempRS));
  echo "</tr></table><BR>";
} // end function view_table

/*-------------------------------------------------------------------  */
function get_strNotUsed($strTable, $other){
  $strNotUsed = singlequery("select ignore_fields from PT_Table_Info where name = '$strTableName'");
  return $strNotUsed;
}  

/*----------------------------------------------------------------------------
ptts2_mail(  ) 
returns the amount of money a family owes
takes the family_id
----------------------------------------------------------------------------- */
function get_amount_due($family_id){
	$dqs = "select sum(amount - paid_amount) from PT_Billing where fid = $family_id and status <> 'paid'";
	$due = singlequery($dqs);
	$cqs = "select sum(amount) from PT_Credits where fid = $family_id";
	$credit = singlequery($cqs);
	
	if(isEmpty($due)) $due = 0;
	if(isEmpty($credit)) $credit = 0;
	
	$due = $due - $credit;
	
	$due = number_format($due, 2, '.', '');
	
	return $due;
}

/*-------------------------------------------------------------------	*/
/* converts a number of seconds to hours-minutes-seconds				*/
/* used to convert Unix time stamp differences.							*/
/*-------------------------------------------------------------------	*/
function get_css_forms(){
	$css_val = singlequery("select other from PTVacations where tid = 19");
	return $css_val;
}

/*----------------------------------------------------------------------------
Update Billing table
Marks 0 dollar invoice as 'Paid'
Created by Sandip on 10/13/2014
----------------------------------------------------------------------------- */
function update_zero_invoice() {
  $BQStr = "Update 'PT_Billing' set status = 'paid' where status <> 'paid' and amount = 0";
  runquery($BQStr);
}


/*----------------------------------------------------------------------------
payment_process($family_id, $amount, $other=NULL  ) 
takes a family id and the amount they pay.  
returns 1 or $error
----------------------------------------------------------------------------- */
function payment_process($family_id, $amount, $comment = NULL, $other=NULL) {

    if(isEmpty($_REQUEST[date])){
		$today = date("Y-m-d"); 
	} else {
		$today = format_date_db($_REQUEST[date]);
	}
	
//	echo "date is $today <BR>";
	
	$temp_fid = $family_id; 
	$temp_pay = $amount;
	$billing_name = singlequery("select billing_name from PT_Family_Info where id = '$temp_fid'");
	$billing_email = singlequery("select billing_email from PT_Family_Info where id = '$temp_fid'");
	$main_email = singlequery("select main_email from PT_Family_Info where id = '$temp_fid'");
      
      $BQStr = "SELECT * FROM `PT_Billing` where status <> 'paid' and fid = '$temp_fid' order by date ASC";
      $cred = singlequery($BQStr);
	  
	  
	  if($BRS = runquery($BQStr)){ 				// if there are unpaid months
	  
	 // echo "BQSTR = $BQStr<BR><BR>";
	  //printRS($BRS);
	  
	  
			while(($BAr = mysql_fetch_array($BRS)) and $temp_pay > 0){     // if there is still money in the payment and money owed 
			  $qid = $BAr['id'];
			  $temp_due = $BAr['amount'] - $BAr['paid_amount'];
			  "<BR><BR>temp due is $temp_due";
			  if($temp_due <= $temp_pay){
				$temp_pay = $temp_pay - $temp_due;
				$qid = $BAr['id'];
				$UQStr = "update PT_Billing set status = 'paid', paid_amount = amount where id = $qid";
				$URS = runquery($UQStr);
	// echo "<BR><BR>ustring is $UQStr";
			  } else {  // if the amount paid can't cover what is owed
				$tot_pay = $BAr['paid_amount'] + $temp_pay;
				$temp_pay = 0;
	
				$URS = runquery("update PT_Billing set status = 'partpaid', paid_amount = $tot_pay where id = $qid");
			  }  // end if 
	
			 } //paid all of the past due bills END WHILE

		
      }
 // echo "value of temp_pau is $temp_pay <BR><BR><BR>";
        if($temp_pay > 0){ //if they overpaid give a credit
          $temp_name = $BAr['name'];
// see if they have a credit already
			$credQS = "select count(*) as count from PT_Credits where fid = $temp_fid"; 
			$cred = singlequery($credQS);
			
			if($cred > 0) { // if they already have a credit, update the value of that credit
					$UQS = "update PT_Credits set amount = (amount + $temp_pay) where fid = $temp_fid";
					$UI = runquery($UQS);
			} else { // if they don't have a credit
		   
          				$CRS = runquery("insert into PT_Credits (fid, amount, date, name) values ($temp_fid, $temp_pay, '$today', (select billing_name from PT_Family_Info where id = $temp_fid))");
			}
        }

// Record the Payment
	  $PayIStr = "Insert into PT_Payments (fid, amount, date, name, comment) values ('$temp_fid',$amount,'$today','$billing_name','$comment')";
      $RS = runquery($PayIStr);  // insert payment query statement 

// email record of payment to us
	$message = "$billing_name ($temp_fid) made a payment in the amount of $amount on $today";
	$subject = "$billing_name ($temp_fid) made a payment in the amount of $amount";
	$strHeader = "From: billing@paulthetutors.com<billing@paulthetutors.com>\r\nReply-to: billing@paulthetutors.com\r\ncc:billing@paulthetutor.com";
	$addparameters = "-fbilling@paulthetutors.com";
	
	ptts2_mail("info@paulthetutors.com",$subject,$message,$strHeader,$addparameters);

// email record of payment to them
	$subject = "Payment Receipt from Paul the Tutor's Education Centers";
	$show_amount = number_format($amount, 2);
	$show_date = date("M jS, Y");
	$message = "$billing_name,
	
Here is a copy of your receipt of payment to Paul the Tutor's Education Centers. 

Name: $billing_name
Account: $family_id
Date: $show_date
Amount: \$$show_amount
Comments: $comment

To see all of your billing and payment history, please go to https://http://www.paulthetutors.com/parents/viewbill.php or contact us directly.

Thanks,

Paul the Tutor's Edcuation Centers
billing@paulthetutors.com
	";
	$strHeader = "From: billing@paulthetutors.com<billing@paulthetutors.com>\r\nReply-to: billing@paulthetutors.com\r\ncc:$main_email,billing@paulthetutor.com";
	$addparameters = "-fbilling@paulthetutors.com";
	
	ptts2_mail($billing_email,$subject,$message,$strHeader,$addparameters);
	
	
	
} //payment_process end	

/*----------------------------------------------------------------------------
saveStripeCustomerId($family_id, $stripe_id); 
takes a family id and the $stripe_id and stores in PT_Strip_Info
----------------------------------------------------------------------------- */
function saveStripeCustomerId($family_id, $customer,$autopay=0) {
	$last_four = $customer->active_card->last4;
	$IQStr = "Insert Into PT_Strip_Info (user_id, stripe_id, date_created,autopay,last_four) values ($family_id, '$customer->id', NOW(),$autopay, '$last_four')";
	
	$insert = runquery($IQStr);
	
	return $insert;
}		

/*----------------------------------------------------------------------------
saveStripeCustomerId($family_id, $stripe_id); 
takes a family id and the $stripe_id and stores in PT_Strip_Info
----------------------------------------------------------------------------- */

function getStripeCustomerId($family_id){
	$sqs = "select stripe_id from PT_Strip_Info where user_id = $family_id and archived = 0 order by id DESC";
	
	
	
	$stripe_id = singlequery($sqs);
	
	return $stripe_id;
	
}
/*----------------------------------------------------------------------------
saveStripeCustomerId($family_id, $stripe_id); 
takes a family id and the $stripe_id and stores in PT_Strip_Info
----------------------------------------------------------------------------- */

function getStripeAutoPay($family_id=NULL,$stripe_id=NULL){
	$where = NULL;
	if(!is_null($family_id)){
		$where = " where famly_id = $family_id ";
	} else if(!is_null($stripe_id)){
		$where = " where stripe_id = $stripe_id ";
	}
	
	if(!is_null($where)){
		$apqs = "select autopay from PT_Strip $where";
		$autopay = singlequery($apqs);
	}
	
	return $autopay;
	
}

	
/*----------------------------------------------------------------------------
get_location_menu($test_id) 
puts the row to get test_id for a form
----------------------------------------------------------------------------- */
function get_location_menu($location_id = NULL, $disName='Location', $varName='location_id', $labelFirst='Choose a Location', $strComment="", $special="required"){ 
?>
    <tr><td align="right">
<?
	echo "$disName<font color=\"#FF0000\">*</font>&nbsp</td><td> ";
	just_location_menu($location_id, $varName, $labelFirst, $strComment);
	
	echo "</td></tr>";
		

	//if the user should be able to enter the rate and pay themselves
	$folder = getfolder('','','');
	if($folder == "admin" and $_SERVER[PHP_SELF] <> '/admin/rate_fam_edit.php'){
		 putCheckBoxInput("Add Rate/Pay Manually", "man_rp", ""); 
	}

}

/*----------------------------------------------------------------------------
just_location_menu($test_id) 
puts the row to get test_id for a form
----------------------------------------------------------------------------- */
function just_location_menu($location_id=NULL, $varName="location_id", $first_label="select a location", $strComment=NULL, $manrp = NULL){

	$loc_qstr = "select id, name from PT_Locations where archived <> 1 order by menu_order, id ";
//	JustSelectFromQuery($loc_qstr, "Location", $varName, $disArray, $location_id, $strComment, $special, $first_label);
	
	
//FUN JustSelectFromQuery($QStr, $disName, $varName, $disArray=NULL, $varSelected=NULL, $strComment=NULL, $special=NULL, $labelFirst=NULL)
	$RS = runquery($loc_qstr);
	while($row = mysql_fetch_array($RS)){
		$disArray[$row[0]] = "$row[1]";
	}
	if($folder == "admin")
		$disArray[-1] = "Add Rate/Pay Manually";
	justSelectInput("Location", $varName, $disArray, $location_id, $strComment, $special, $first_label);
	
}	


/*-------------------------------------------------------------------
/*-------------------------------------------------------------------
/*-------------------------------------------------------------------
/*-------------------------------------------------------------------
/*-------------------------------------------------------------------
/*-------------------------------------------------------------------
/*-------------------------------------------------------------------
*******ALL OLD FILES FROM THE OLD PTTIncludes.phtlm START HERE*******
-------------------------------------------------------------------	*
-------------------------------------------------------------------	*
-------------------------------------------------------------------	*
-------------------------------------------------------------------	*
-------------------------------------------------------------------	*
-------------------------------------------------------------------	*
-------------------------------------------------------------------	*/



/*-------------------------------------------------------------------

puts the billng info for a family based on the family id (fid).

Only shows the unpaid bills if $status = "unpaid"

-------------------------------------------------------------------	*/

Function send_passed_due($fid,$month,$year){

	$PDQStr = "select month, year, amount, paid_amount from PT_Billing where fid = $fid and status <> 'paid' and (year < $year or (month < $month and year = $year)) order by year, month";

	$PDRS = runquery($PDQStr);

	$num_rows = mysql_num_rows($PDRS);

	if($num_rows > 0){

		$FIQStr = "select billing_name, billing_email from PT_Family_Info where id = $fid";

		$FRS = runquery($FIQStr);

		$Far = mysql_fetch_array($FRS);

		$TBill = 0;

		$PDStr = "You have bills from the following months:\n";

		while($PDar = mysql_fetch_array($PDRS)){

			$timeint = mktime(0, 0, 0, $PDar["month"], 15, $PDar["year"]);

	

			$MonDue = $PDar["amount"] - $PDar["paid_amount"];

			$PDmonth = $PDar["month"];

			$PDyear = $PDar["year"];

			$strMY =  date("M - Y", $timeint);                 

			$TBill = $TBill + $MonDue;

			$PDamount = number_format($MonDue,2,".",",");

			$PDStr = $PDStr . "      $strMY: \$$PDamount \n";

		}

		$TBillstr = number_format($TBill,2,".",",");

$Bstr = "$Far[billing_name],\n\n";

$Bstr = $Bstr . "Your total bill due is: \$$TBillstr \n\n" . $PDStr;



$strBody = "$Bstr

To see any invoice, log on at www.paulthetutors.com/parents

To Pay By Credit Card:
To pay be credit card go to www.paulthetutors.com/parents/strippay_action2.php or to pay without logging in, go to www.paulthetutors.com/ccpay and enter your account number $sid and amount you want to pay.

To Pay By Check:
- Please make check payable to: Paul the Tutor's
- Please put your account number on the check (Acct: $fid)
- Mail your check to:

 Paul the Tutor's Education Center
 4235 Piedmont Ave.
 Oakland, CA 95611

If you have any questions, please do not hesitate to call or e-mail me.\n\nThank You,\n\nPaul the Tutor's Education Center\n(510) 730-0390\ninfo@paulthetutors.com \nwww.paulthetutors.com";



			$strSubject = "Your bill from Paul The Tutor";



	$strHeader = "From: billing@paulthetutors.com<Paul the Tutor>\r\nReply-to: billing@paulthetutors.com\r\ncc:billing@paulthetutor.com";
$addparameters = "-fbilling@paulthetutors.com";



	mail($Far[billing_email], $strSubject, $strBody, $strHeader,$addparameters);

//	mail('paul@paulthetutor.com', $strSubject, $strBody, $strHeader);

	echo "<strong>$Far[billing_name]</strong><BR>A passed due notice was sent to  <BR><BR>";

  } //end if bills are passed due

  



} // end function	



/*-------------------------------------------------------------------

puts the billng info for a family based on the family id (fid).

Only shows the unpaid bills if $status = "unpaid"

-------------------------------------------------------------------	*/

Function put_fam_billing_info($fid,$status){



if($status == "unpaid") {

$whereclause = "and status = 'notpaid'";

}



$QStr = "select month, year, amount, status, date from PT_Billing where fid = $fid $whereclause order by date desc";

$BIRS = runquery($QStr);



?>

<hr>		    

			<span class="Head2">These are the payments which I have received and processed.  It may not reflect checks you have sent recently.</span>			<table border="2" align="center">

  <tr>

    <td width="83"><div align="center"><strong>Bill</strong></div></td>

    <td width="88"><div align="center"><strong>Amount</strong></div></td>

    <td width="105"><div align="center"><strong>Status</strong></div></td>

    <td width="105"><div align="center"><strong>Action</strong></div></td>

  </tr>

  

 <? 	while($arBI = mysql_fetch_array($BIRS)){ 

 $monthname = date(M, mktime(0,0,0,$arBI[0], 15, 2000));

 $monnum = $arBI[0];

 $yearnum = $arBI[1]

 ?>

 

  <tr>

    <td>

	<? echo " $monthname - $arBI[1]";?>

	</td>

    <td>$<?=$arBI['amount'];?></td>

    <td><?=$arBI['status'];?></td>

	 <td>

	<a href="viewbillaction.php?month=<?=$monnum;?>&year=<?=$yearnum;?>"  target="_blank" >

	See Invoice

	</a>

	</td>



  </tr>

 <?}?>

</table>

<? }//end function







/*-------------------------------------------------------------------

	connects to the mysql database for paulthetutor.com
	note: assumption is connecting twice to database does not cause errors

-------------------------------------------------------------------	*/

Function MySQL_PaulTheTutor_Connect() {
	
	$dbh=mysql_connect ("mysql.paulthetutors.com", "paulthetutors", "cartruck32") or die ('I cannot connect to the database because: ' . mysql_error());

	//$dbh=mysql_connect ("localhost", "root", "") or die ('I cannot connect to the database because: ' . mysql_error());

	mysql_select_db ("paulth40_db"); 

	$mysqli = new mysqli("mysql.paulthetutors.com", "paulthetutors", "cartruck32", "paulth40_db");
	if ($mysqli->connect_errno) {
		echo "Failed to connect to MySQLi: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
	}
	
	return $mysqli;

}

/*-------------------------------------------------------------------

	connects to the mysql database for paulthetutor.com

-------------------------------------------------------------------	*/

Function MySQLi_PaulTheTutor_Connect() {

	$dbh=mysql_connect ("mysql.paulthetutors.com", "paulthetutors", "cartruck32") or die ('I cannot connect to the database because: ' . mysql_error());

	//$dbh=mysql_connect ("localhost", "root", "") or die ('I cannot connect to the database because: ' . mysql_error());

	mysql_select_db ("paulth40_db"); 

	$mysqli = new mysqli("mysql.paulthetutors.com", "paulthetutors", "cartruck32", "paulth40_db");
	if ($mysqli->connect_errno) {
		echo "Failed to connect to MySQLi: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
	}
	
	return $mysqli;

}



/*-------------------------------------------------------------------

	returns a string strBack which can be put in links

	to return to the home page level

-------------------------------------------------------------------	*/

Function get_strBack() {

	$homefinder = $_SERVER['PHP_SELF'];

	

	$numFolders = substr_count("$homefinder", "/") - 1;

	$strBack = "";

	$i = 0;

	

	while($i < $numFolders){

		$strBack = $strBack . "../";

		$i = $i + 1;

	}

	return $strBack;

}	



/*-------------------------------------------------------------------

	gets the name of the page with htm on the end as opposed to php

-------------------------------------------------------------------	*/

Function phptohtm() {

$page_name = $_SERVER['PHP_SELF'];

	$arPage = explode("/",$page_name);

	$numSlash = substr_count("$page_name", "/");

	$page_name = $arPage[$numSlash];

	$page_name = str_replace("php", "htm", $page_name);

	$page_name = str_replace("/", "", $page_name);

	return $page_name;

}	







/*-------------------------------------------------------------------	*/

/* gets the array with a students billing information for a month	*/

/* returns a array with

	arBillInfo[date,rate,hours,special,comments]*/

/*-------------------------------------------------------------------	*/





//get the schedule for the students: day of week, hours and rate

Function getarBillInfo($month, $year, $sid) {



	$first_of_month = "$year/$month/1";

	if($month <12){

		$next_month = $month + 1;

		$first_of_nextmonth = "$year/$next_month/1";

	} else {

		$next_year = $year + 1;

		$first_of_nextmonth = "$next_year/1/1";

	}	

	$i = 0;

	$QStr = "select name, dow, hours, rate, start_date, end_date, start_time from PTSchedInfo where sid = $sid and (start_date < '$first_of_nextmonth' and end_date >= '$first_of_month')";



	if(!($SchedInfoRS = mysql_query($QStr))){

		echo "$QStr <br>" . mysql_error();

	}

// first set up the schedule each scheduled day of the week assuming everything is normal

	while($arSI = mysql_fetch_array($SchedInfoRS)){

		$tempday=0;

		$arStartDate = explode("-", $arSI[start_date]);

		$arEndDate = explode("-", $arSI[end_date]);



//find the date the first day of the week of the month

$lastofmonth = date("t", mktime (0,0,0,$month,11,$year));

		do {

		

			$tempday = $tempday + 1;



			if($tempday == $lastofmonth){

				break;

			}	

			

			if(mktime(0,0,0,$month,$tempday,$year) > mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])){

				break;

			}	

			

			

		} while((date("l", mktime(0,0,0,$month,$tempday,$year)) <> $arSI[dow]) or (mktime(0,0,0,$month,$tempday,$year) < mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])));

//echo "dow is $arSI[dow]<BR>";



//echo "tempdate is $tempday<BR>";

//echo "mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])";







if(date("l", mktime (0,0,0,$month,$tempday,$year)) == $arSI[dow]){ //if we didn't find any day that works, don't add anything to the array

		do {



// printarray($arSI);

			$printday = date("d", mktime (0,0,0,$month,$tempday,$year));



			$arBillInfo[$printday][numday] = $tempday;

			$arBillInfo[$printday][date] = date("dS \of M", mktime (0,0,0,$month,$tempday,$year));

			$arBillInfo[$printday][hours] = $arSI[hours];

			$arBillInfo[$printday][rate] = $arSI[rate];

			$arBillInfo[$printday][start_time] = $arSI[start_time];

			$arBillInfo[$printday][special] = "&nbsp;";

			$arBillInfo[$printday][comments] = "&nbsp;";

			



			$tempday = $tempday + 7;

		} while(date("n", mktime (0,0,0,$month,$tempday,$year)) == $month and (mktime(0,0,0,$month,$tempday,$year) <= mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])) );



	$useRate = $arSI[rate];

	$useHours = $arSI[hours];

} //end if that ensure that the first date found is a usable date.	

	}

// end of basic schedule set up



// remove schedules from vacation days

	$QStr = "select id, start_date, end_date from PTVacations where start_date < '$first_of_nextmonth' and end_date >= '$first_of_month'";

	if(!($VacRS = mysql_query($QStr))){

		echo "$QStr <br>" . mysql_error();

	}

 	while($arVac = mysql_fetch_array($VacRS)){

		$arStartDate = explode("-", $arVac[start_date]);

		$arEndDate = explode("-", $arVac[end_date]);



//if the vacation started before the start of this month, start vacation on the first day of this month

		if (mktime(0,0,0,$month,1,$year) > mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])) {

//			echo "use first of month for $arVac[start_date] <BR>";

			$tempdate = 01;

		} else { 

//			echo "use Vacation's start date for $arVac[start_date]<BR>";

			$tempdate = $arStartDate[2];

		}

		

//		echo "mktime(0,0,0,$month,1,$year)   and   mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])  <BR><BR>";

// get the last day of the month

$last_day_month = date('j',mktime(0, 0, 0, $month+1, 0, $year));	

//clear the dates of the vacation		

		do {

			unset($arBillInfo[$tempdate]);

			unset($arBillInfo["0" . $tempdate]);

			$tempdate = $tempdate +1;

			

		} while (($tempdate <= $last_day_month) and (mktime(0,0,0,$month,$tempdate,$year) <= mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])));		



	

	} //end while we have vacations to remove

	

// end removed vacation days				





// get the missed appointments.  These are the appointments that are not billed for

$QStr = "select date from PTMissedApp where month(date) = $month and year(date) = $year and (sid = $sid or sid = 0)";



		if(!($MARS = mysql_query($QStr))){

			echo "$QStr <br>" . mysql_error();

		}



	/*

	get the changes to the schedule

	These are

		1) late cancelation - cut rate inhalf (comment "Late Cancel")

		2) no show - just note under comment "No Show"

		3) changed hours - change only the hours (No Comments)

		4) special rate - change the rate & hours if they are there (comment as required)

		5) rescheduling fee - no hours, just charge the rescheduling fee (comments "Rescheduling Fee")

		6) cancel no charge - mark as a cancelation, 0 hours and fee (comment = "Cancelation No Charge")

	*/



		$QStr = "select date, hours, rate, special, comments from PTChangedApp where month(date) = $month and year(date) = $year and  (sid = $sid or sid = 0)";



//	echo "changed qstr is $QStr <BR><BR><BR>";



		if(!($ChARS = mysql_query($QStr))){

			echo "$QStr <br>" . mysql_error();

		}

// printRS($ChARS);

		while($arChA = mysql_fetch_array($ChARS)){





			$arDate = explode("-", $arChA[date]);

			$printday = $arDate[2];







	// ensure that changes are being made to a date that tutor worked

			if(isset($arBillInfo[$printday][hours])){



	// put the date into the array

				$arBillInfo[$printday][date] = date("dS \of M", mktime (0,0,0,$arDate[1],$arDate[2],$arDate[0]));



	// add the comments if they are set

				if(!(isEmpty($arChA[comments]))){

					$arBillInfo[$printday][comments] = $arChA[comments];

				}

	// put the special in, and make other appropriate changes

				if(!(isEmpty($arChA[special]))){

	// make sure that we $arChA[special] = trim($arChA[special])



				$arBillInfo[$printday][special] = $arChA[special];

				switch($arChA[special]){

					case "late cancelation":

						$arBillInfo[$printday][rate] = $arBillInfo[$printday][rate] / 2;

						if((!(isEmpty($arChA[hours]))) and $arChA[hours] > 0){

							$arBillInfo[$printday][hours] = $arChA[hours];

						}

						break;

					case "changed hours":

						$arBillInfo[$printday][hours] = $arChA[hours];

						$arChA[special] = "";

						break;

					case "special rate":

						$arChA[special] = "";

						$arBillInfo[$printday][rate] = $arChA[rate];

						break;

					case "rescheduling fee":

						$arBillInfo[$printday][hours] = 1;

						$arBillInfo[$printday][rate] = 10;

						break;

					case "cancelation no charge":

						$arBillInfo[$printday][rate] = 0;

						break;

				}//	switch

				} // is special is set

			} // if

		}		// while appointments to change

// end of changed appointments



// get the added appts

	$QStr = "select date, hours, rate, start_time, comments from PTAddedApp where year(date) = $year and month(date) = $month  and (sid = $sid)";

	if(!($AdARS = mysql_query($QStr))){

		echo "$QStr <br>" . mysql_error();

	}

	while($arAdA = mysql_fetch_array($AdARS)){



		$arDate = explode("-", $arAdA[date]);

		$printday = $arDate[2];



		$arBillInfo[$printday][date] = date("dS \of M", mktime (0,0,0,$arDate[1],$arDate[2],$arDate[0]));



		$arBillInfo[$printday][special] = "&nbsp;";

		$arBillInfo[$printday][comments] = $arAdA[comments];

		$arBillInfo[$printday][start_time] = $arAdA[start_time];



// if the rate is not put, use the standard rate

		if(($arAdA[rate] > 0) and $arAdA[rate] <> null){

			$arBillInfo[$printday][rate] = $arAdA[rate];

		} else {

			$arBillInfo[$printday][rate] = $useRate;

		}



//if the hours are left blank, insert the normal hours

		if(($arAdA[hours] > 0) and $arAdA[hours] <> null){

			$arBillInfo[$printday][hours] = $arAdA[hours];

		} else {

			$arBillInfo[$printday][hours] = $useHours;

		}

	}

// end of added appointments

		

		// remove missed appointments from arBillInfo

		while($arDates = mysql_fetch_array($MARS)){

			$arDate = explode("-", $arDates[date]);

			$printday = $arDate[2];



			unset($arBillInfo[$printday]);

		}







		

if(isset($arBillInfo)){  // if there is an array, sort it

	ksort($arBillInfo);

}



return $arBillInfo;



} //END FUNCTION

/*-------------------------------------------------------------------

	puts the end of the new paulthetutor.com pages

-------------------------------------------------------------------	*/
  
Function put_new_footer() {  ?>

	  </td>

    </tr>

  </table>

<BR><BR>

</body>

</html>







<? }

/*************************************************************************************************************/ 

/* Function return info about added appts for the client calendar*/  

/*************************************************************************************************************/ 

function getClientCalInfo($month, $year, $sid, $tid=1) 

 {



	if($month>1)

	{

		$prev_month=$month-1;

		$twt_of_prevmonth="$year-$prev_month-23";

	}

	else

	{

		$prev_year=$year-1;

		$twt_of_prevmonth="$prev_year-12-23";

	}

	

	

if($month <12){
		$next_month = $month + 1;
		$sixth_of_nextmonth = "$year-$next_month-06";
	} else {
		$next_year = $year + 1;
		$sixth_of_nextmonth = "$next_year-01-06";
	}	
	$i = 0;
	$QStr = "select name, dow, hours, rate, start_date, end_date, start_time from PTSchedInfo where sid = $sid and (start_date < '$sixth_of_nextmonth' and end_date >= '$twt_of_prevmonth') and tid=$tid";



	if(!($SchedInfoRS = mysql_query($QStr))){
		echo "$QStr <br>" . mysql_error();

	}

// first set up the schedule each scheduled day of the week assuming everything is normal

	while($arSI = mysql_fetch_array($SchedInfoRS)){
		$tempday=0;
		$arStartDate = explode("-", $arSI['start_date']);
		$arEndDate = explode("-", $arSI['end_date']);

//find the date the first day of the week of the month
$lastofmonth = date("t", mktime (0,0,0,$month,11,$year));
		do {
			$tempday = $tempday + 1;
			if($tempday == $lastofmonth){

				break;

			}	

			if(mktime(0,0,0,$month,$tempday,$year) > mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])){
				break;
			}	
		} while((date("l", mktime(0,0,0,$month,$tempday,$year)) <> $arSI[dow]) or (mktime(0,0,0,$month,$tempday,$year) < mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])));

//echo "dow is $arSI[dow]<BR>";
//echo "tempdate is $tempday<BR>";
//echo "mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])";

if(date("l", mktime (0,0,0,$month,$tempday,$year)) == $arSI[dow]){ //if we didn't find any day that works, don't add anything to the array
		do {
// printarray($arSI);
			$printday = date("d", mktime (0,0,0,$month,$tempday,$year));
			$arBillInfo[$printday]['numday'] = $tempday;
			$arBillInfo[$printday]['date'] = mktime (0,0,0,$month,$tempday,$year);
			$arBillInfo[$printday]['hours'] = $arSI['hours'];
			$arBillInfo[$printday]['rate'] = $arSI['rate'];
			$arBillInfo[$printday]['start_time'] = $arSI['start_time'];
			$arBillInfo[$printday]['special'] = "&nbsp;";
			$arBillInfo[$printday]['comments'] = "&nbsp;";
			$tempday = $tempday + 7;
		} while(date("n", mktime (0,0,0,$month,$tempday,$year)) == $month and (mktime(0,0,0,$month,$tempday,$year) <= mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])) );
	$useRate = $arSI[rate];
	$useHours = $arSI[hours];

} //end if that ensure that the first date found is a usable date.	
	} // end of basic schedule set up

// remove schedules from vacation days

	$QStr = "select id, start_date, end_date from PTVacations where start_date < '$sixth_of_nextmonth' and end_date >= '$twt_of_prevmonth' and tid=$tid";
	if(!($VacRS = mysql_query($QStr))){
		echo "$QStr <br>" . mysql_error();
	}

 	while($arVac = mysql_fetch_array($VacRS)){
		$arStartDate = explode("-", $arVac['start_date']);
		$arEndDate = explode("-", $arVac['end_date']);


//if the vacation started before the start of this month, start vacation on the first day of this month
		if (mktime(0,0,0,$month,1,$year) > mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])) {
//			echo "use first of month for $arVac[start_date] <BR>";
			$tempdate = 01;
		} else { 
//			echo "use Vacation's start date for $arVac[start_date]<BR>";
			$tempdate = $arStartDate[2];
		}
//		echo "mktime(0,0,0,$month,1,$year)   and   mktime(0,0,0,$arStartDate[1],$arStartDate[2],$arStartDate[0])  <BR><BR>";

// get the last day of the month
$last_day_month = date('j',mktime(0, 0, 0, $month+1, 0, $year));	

//clear the dates of the vacation		
		do {
			unset($arBillInfo[$tempdate]);
			unset($arBillInfo["0" . $tempdate]);
			$tempdate = $tempdate +1;
		} while (($tempdate <= $last_day_month) and (mktime(0,0,0,$month,$tempdate,$year) <= mktime(0,0,0,$arEndDate[1],$arEndDate[2],$arEndDate[0])));		
	} //end while we have vacations to remove
// end removed vacation days				

// get the missed appointments.  These are the appointments that are not billed for
$QStr = "select date from PTMissedApp where date>=$twt_of_prevmonth and date<=$sixth_of_nextmonth and (sid = $sid or sid = 0) and tid=$tid";
		if(!($MARS = mysql_query($QStr))){
			echo "$QStr <br>" . mysql_error();
		}

	/*
	get the changes to the schedule
	These are
		1) late cancelation - cut rate inhalf (comment "Late Cancel")
		2) no show - just note under comment "No Show"
		3) changed hours - change only the hours (No Comments)
		4) special rate - change the rate & hours if they are there (comment as required)
		5) rescheduling fee - no hours, just charge the rescheduling fee (comments "Rescheduling Fee")
		6) cancel no charge - mark as a cancelation, 0 hours and fee (comment = "Cancelation No Charge")
	*/

		$QStr = "select date, hours, rate, special, comments from PTChangedApp where date>='$twt_of_prevmonth' and date<='$sixth_of_nextmonth' and  (sid = $sid or sid = 0) and tid=$tid";

//	echo "changed qstr is $QStr <BR><BR><BR>";
		if(!($ChARS = mysql_query($QStr))){
			echo "$QStr <br>" . mysql_error();
		}
// printRS($ChARS);
		while($arChA = mysql_fetch_array($ChARS)){

			$arDate = explode("-", $arChA[date]);
			$printday = $arDate[2];

	// ensure that changes are being made to a date that tutor worked
			if(isset($arBillInfo[$printday][hours])){

	// put the date into the array
				$arBillInfo[$printday][date] = mktime (0,0,0,$arDate[1],$arDate[2],$arDate[0]);

	// add the comments if they are set
				if(!(isEmpty($arChA[comments]))){
					$arBillInfo[$printday][comments] = $arChA[comments];
				}

	// put the special in, and make other appropriate changes
				if(!(isEmpty($arChA[special]))){

	// make sure that we $arChA[special] = trim($arChA[special])
				$arBillInfo[$printday][special] = $arChA[special];
				switch($arChA[special]){
					case "late cancelation":
						$arBillInfo[$printday][rate] = $arBillInfo[$printday][rate] / 2;
						if((!(isEmpty($arChA[hours]))) and $arChA[hours] > 0){
							$arBillInfo[$printday][hours] = $arChA[hours];
						}
						break;

					case "changed hours":
						$arBillInfo[$printday][hours] = $arChA[hours];
						$arChA[special] = "";
						break;

					case "special rate":
						$arChA[special] = "";
						$arBillInfo[$printday][rate] = $arChA[rate];
						break;

					case "rescheduling fee":
						$arBillInfo[$printday][hours] = 1;
						$arBillInfo[$printday][rate] = 10;
						break;

					case "cancelation no charge":
						$arBillInfo[$printday][rate] = 0;
						break;

				}//	switch
				} // is special is set
			} // if
		}		// while appointments to change
// end of changed appointments

// get the added appts
	$QStr = "select date, hours, rate, start_time, comments from PTAddedApp where date>='$twt_of_prevmonth' and date<='$sixth_of_nextmonth' and (sid = $sid) and tid=$tid";
	if(!($AdARS = mysql_query($QStr))){
		echo "$QStr <br>" . mysql_error();
	}

	while($arAdA = mysql_fetch_array($AdARS)){
		$arDate = explode("-", $arAdA['date']);
		$printday = $arDate[2];
		$arBillInfo[$printday]['date'] = mktime (0,0,0,$arDate[1],$arDate[2],$arDate[0]);
		$arBillInfo[$printday]['special'] = "&nbsp;";
		$arBillInfo[$printday]['comments'] = $arAdA['comments'];
		$arBillInfo[$printday]['start_time'] = $arAdA['start_time'];

// if the rate is not put, use the standard rate
		if(($arAdA['rate'] > 0) and $arAdA['rate'] <> null){
			$arBillInfo[$printday]['rate'] = $arAdA['rate'];
		} else {
			$arBillInfo[$printday]['rate'] = $useRate;
		}

//if the hours are left blank, insert the normal hours

		if(($arAdA['hours'] > 0) and $arAdA['hours'] <> null){
			$arBillInfo[$printday]['hours'] = $arAdA['hours'];
		} else {
			$arBillInfo[$printday]['hours'] = $useHours;
		}
	} // end of added appointments

		// remove missed appointments from arBillInfo
		while($arDates = mysql_fetch_array($MARS)){
			$arDate = explode("-", $arDates[date]);
			$printday = $arDate[2];
			unset($arBillInfo[$printday]);
		}

if(isset($arBillInfo)){  // if there is an array, sort it
	ksort($arBillInfo);
} else $arBillInfo = false;

return $arBillInfo;
} //END FUNCTION







/*-------------------------------------------------------------------	*/

/* gets the student's information					*/

/*-------------------------------------------------------------------	*/



Function getStudentsName($family_id) {

	$SName = get_family_snames($family_id);


	return $SName;



} //END FUNCTION



/*-------------------------------------------------------------------	*/

/* check password matches student id					*/

/*-------------------------------------------------------------------	*/



Function checkStudentsPWord($sid, $pword) {

	$QStrsi = "select count(*) as counter from PT_Family_Info where id = $sid and password = '$pword'";

/*	if(!($siRS = mysql_query($QStrsi))){

		echo "QStr:  $QStrsi <BR>" . mysql_error() . "<BR><BR>";

	}

*/



	$siRS = mysql_query($QStrsi);

	$arSInfo = mysql_fetch_array($siRS);



	return $arSInfo[counter];



} //END FUNCTION







/*-------------------------------------------------------------------	*/

/* gets the courses and put them into an array					*/

/*-------------------------------------------------------------------	*/



Function getCourses() {

	$arCourses = array('Mathematics', 'Physics', 'Chemistry', 'Biology', 'SAT/PSAT prep', 'English', 'History', 'Spanish', 'French', 'Other');



	return $arCourses;



} //END FUNCTION








/*-------------------------------------------------------------------	*/
/* gets the information for the students section					*/
/*-------------------------------------------------------------------	*/

	Function getstudentsecinfo($sid){
		$QStr = "select  last_name, first_name, email, fid from PTStudentInfo_New where id = $sid";

		if(!($RS = mysql_query($QStr))){
			echo "$QStr <br>" . mysql_error();
		}
		$arRow = mysql_fetch_array($RS);
	return($arRow);

}
/*-------------------------------------------------------------------	*/
/* gets the information for the students section					*/
/*-------------------------------------------------------------------	*/
Function getMainName($fid){
	$QStr = "select mother, father, guardian, main_contact, billing_contact from PT_Family_Info where id = $fid";

	$FRS = mysql_query($QStr);	

	$famAR = mysql_fetch_array($FRS);

	$main_name = $famAR[$famAR['main_contact']];

return($main_name);	

}



function putParentsLinks(){  ?>

		<span class="Head2">Parents Links</span>	  <br>

	  <a href="http://www.paulthetutor.com/signup/index_new.php">parents home page</a> 

	  <br>

	  <a href="http://www.paulthetutor.com/signup/viewbill.php">view a bill</a> 

	  <br><br>

      <a href="http://www.paulthetutor.com/contact.php" target="_blank">Contact Paul</a><br>

	  <a href="logout.php">log out</a>

	  <br>



<?

}

/**************************************************

 Deal with added or deleted appointments

 ***************************************************/

function client_del($del_date, $del_time, $del_fid, $del_tid) {

	$MQStr = "INSERT INTO PTMissedApp (sid, date, tid) VALUES ('$del_fid', '$del_date', '$del_tid')";

	$MRS = runquery($MQStr);

	

	$start_time_24h =  date("H:i:s", strtotime($del_time));

	$DQStr = "DELETE from PTAddedApp where sid = '$del_fid' and date = '$del_date' and tid='$del_tid' and start_time='$start_time_24h'";

	$DRS = runquery($DQStr);

	$snames = getstudentsname($del_fid);

	/*find at which tutor the app is canceled:*/

	$res=runquery("select first_name, last_name, email from PT_Tutors where id='$del_tid'");

	$row=mysql_fetch_row($res);

	$tut_name= $row[0];

	/*tutor's email address*/

	$tut_email=$row[2];

	$msgtopaul = "$snames cancelled appointment at $tut_name on $del_date at $del_time.";

	$strHeader = "From: cancel@paulthetutor.com<PTT Cancelation>\r\n";

//	mail('paul@paulthetutor.com', $msgtopaul, $msgtopaul, $strHeader);

	/*send mail to tutor which appt was canceled(line below):*/

	//mail($tut_email, $msgtopaul, $msgtopaul, $strHeader);

	

	return "Confirming cancelation of appointment with $tut_name, on $del_date at $del_time.";

}



function client_add($add_date, $start_time, $add_fid, $hours, $rate, $tid) {

	if(isEmpty($tid)) {

		$tid = 1;

	}

	$start_time = $start_time;

	

	if(isEmpty($hours)){

		$hours = 1;

	}	

	$start_time_24h =  date("H:i:s", strtotime($start_time));   //convert ampm time in format appropriate for mysql db(i.e. 24h format)

	$AQStr = "INSERT INTO PTAddedApp (sid, date, hours, rate, start_time, tid) VALUES ('$add_fid', '$add_date', '$hours', '$rate', '$start_time_24h', '$tid')";

	$ARS = runquery($AQStr);

	$DQStr = "DELETE from PTMissedApp where sid = '$add_fid' and date = '$add_date' and tid='$tid'";

	$DRS = runquery($DQStr);



	/*find at which tutor the app is scheduled:*/

	$res=runquery("select first_name, last_name, email from PT_Tutors where id='$tid'");

	$row=mysql_fetch_row($res);

	$tut_name= $row[0] . " T.";

	$tut_email=$row[2];

	$snames = getstudentsname($add_fid);

	$msgtopaul = "$snames added an appointment on $add_date with $tut_name, at $start_time for $hours hours of tutoring.";

	$strHeader = "From: add@paulthetutor.com<PTT Addition>\r\n";

	

	//mail('paul@paulthetutor.com', $msgtopaul, $msgtopaul, $strHeader);

	/*send mail with whom the appt was added(line below):*/

	//mail($tut_email, $msgtopaul, $msgtopaul, $strHeader);

	return"Confirming appointment with $tut_name, on $add_date at $start_time.";

	

}



/**************************************************
 show_sched_details 
 inputs: schedule id 
 returns: nothing
 ***************************************************/


function return_sched_details($shed_id,$style = "string", $css_style = "sched_table_style"){
	
	$qstr = "select id, (select CONCAT(first_name, ' ' , last_name) from PTStudentInfo_New st where st.id = sc.student_id) as Student, (select CONCAT(first_name, ' ', last_name) from PT_Tutors t where t.id = sc.tid) as Tutor,  dow as Day, Time_Format(start_time,'%r') as Time, hours as Hours, start_date as 'Start Date', end_date as 'End_Date',(select short_name from PT_Locations L where L.id = sc.location_id) as Location from PTSchedInfo2 sc where id = $shed_id";
	
	$RS = runquery($qstr);

	if($rowar = mysql_fetch_assoc($RS)){
		while(list($key, $value) = each($rowar)){
			if($style == "string") 
				$return = $return . " <br /> <strong>$key:</strong> $value ";
		}
	}
	return $return;	

}

/**************************************************

 inputs: A phone number formatted in anyway.
 returns: a nicely formatted phone number 
 ***************************************************/

function format_phoneN($phone) {

	$phone = preg_replace("/[^0-9]/", "", $phone);

    if(strlen($phone) == 7)

        return preg_replace("/([0-9]{3})([0-9]{4})/", "$1-$2", $phone);

    elseif(strlen($phone) == 10)

        return preg_replace("/([0-9]{3})([0-9]{3})([0-9]{4})/", "($1) $2-$3", $phone);

    else
    	
        return $phone;

}


?>